### ISSUE TITLE
I couldn't create a .vsix file

### ISSUE THREAD

**Issue by 4lev** [rjmacarthy/twinny#1]
npm run package

> twinny@0.0.3 package
> webpack --mode production --devtool hidden-source-map

    [webpack-cli] Compiler starting... 
    [webpack-cli] Compiler is using config: '/twinny/webpack.config.js'
    [webpack-cli] Compiler finished
assets by status 226 KiB [cached] 1 asset
modules by path ./node_modules/ 415 KiB
  javascript modules 271 KiB 61 modules
  json modules 143 KiB
    ./node_modules/openai/package.json 470 bytes [built] [code generated]
    ./node_modules/mime-db/db.json 143 KiB [built] [code generated]
modules by path ./src/*.ts 4.87 KiB
  ./src/extension.ts 919 bytes [built] [code generated]
  ./src/completion.ts 3.97 KiB [built] [code generated] [3 errors]
+ 12 modules

ERROR in /twinny/src/completion.ts
./src/completion.ts 135:12-21
[tsl] ERROR in /twinny/src/completion.ts(135,13)
      TS7053: Element implicitly has an 'any' type because expression of type '0' can't be used to index type 'CreateCompletionResponseChoicesInner'.
  Property '0' does not exist on type 'CreateCompletionResponseChoicesInner'.
 @ ./src/extension.ts 5:21-44

ERROR in /twinny/src/completion.ts
./src/completion.ts 136:26-31
[tsl] ERROR in /twinny/src/completion.ts(136,27)
      TS2339: Property 'slice' does not exist on type 'CreateCompletionResponseChoicesInner'.
 @ ./src/extension.ts 5:21-44

ERROR in /twinny/src/completion.ts
./src/completion.ts 136:42-48
[tsl] ERROR in /twinny/src/completion.ts(136,43)
      TS2339: Property 'length' does not exist on type 'CreateCompletionResponseChoicesInner'.
 @ ./src/extension.ts 5:21-44

3 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.88.2 compiled with 3 errors in 4669 ms

**Comment by rjmacarthy** [comment]
Thanks for the report, it seems I am using out dated `openai.d.ts` I will fix it.
