### ISSUE TITLE
The action buttons do not show up

### ISSUE THREAD

**Issue by AntonKrug** [rjmacarthy/twinny#100]
**Describe the bug**
The action buttons do not show up on the Windows 10.
I was thinking that the edit template fix could fix this and was not paying attention to yet as i was thinking it was not related, but the buttons did not show up even in the previous bug report

**To Reproduce**
1. Go to any code and select chunk of code
2. Do not see any buttons rendered
3. Type something what the button would do
4. Outputs still correct, but the buttons are not present:

**Expected behavior**
See 'Explain', 'Refactor' button options

**Screenshots**
![image](https://github.com/rjmacarthy/twinny/assets/30338596/4a8b77c5-5e61-4b29-8833-30f4144f0dac)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 122

**Comment by rjmacarthy** [comment]
Hey, thanks @AntonKrug for the issue.

I checked on Windows today and it was working for me.  I just released a new version `3.5.3` which includes a reset templates button to defaults, the names of the templates should be `kebab-case.hbs` please let me know if it helps.

Many thanks.

**Comment by AntonKrug** [comment]
`Manage twinny templates` and clicking `reset button` there solved the problem, thank you very much
