### ISSUE TITLE
Model profiles dropdown

### ISSUE THREAD

**Issue by AntonKrug** [rjmacarthy/twinny#102]
**Is your feature request related to a problem? Please describe.**
I tend to switch between 7b/13b models on day-to-day, sometimes switch to 70b for more tricky problems, and for non coding tasks I switch to completely different models. Right now it all has to always be done through settings.

**Describe the solution you'd like**
A way to configure model `profiles` in the settings where i can give some model settings a nicknme, for example `7b-dayToDay`, `70b-slow` or `documentation` and then have these nicknames listed on top twinny as a dropdown (next to the other twinny buttons), allowing me quickly switch/swap models without the need to always go to settings

**Describe alternatives you've considered**
Manually always switching models, but it gets tedious because the 70b models i use are only for one-off tasks and then switch to 7b/13b back again

**Comment by rjmacarthy** [comment]
Hey, I added this in the latest version if you're using Ollama there is a model select now.

**Comment by AntonKrug** [comment]
Nevermind, my ollama was not running, so now i see the options but still i see a problem there.

**Comment by AntonKrug** [comment]
Thank you very much for the feature, but still it's similarly cumborsome to the settings page.

You want to switch between 13b and 7b models often, so you need to click on the icon, then clicking on the dropdown, scrolling through many models including ones which are irelevant in twinny lika llava, then do it again for FIM and then click on the button again to hide the dropdowns as they take a lot of space and then again switch back.

That's lot of clicks, i was asking to have something always present which instantly on first click will show the model options (not just shows 2 separate dropdowns for them to be clicked separately), this is almost as bad as having settings tab opened with filter on models and doing it by hand there.

So current selector has problem that you do not have your own hand curated list with your own meanifgul names, you have lots of selection options which are irelavant in vscode plugin context and you have to do it. You have to do many clicks to switch.

But with a dedicate dropdown (or submenu icon) similar to this:
![image](https://github.com/rjmacarthy/twinny/assets/30338596/3ee8ddd8-7ae0-48d9-9f69-36c18d3aff8f)
you could just clik on one icon, see your 2-3 hand crafted options, and they would update both chat/fim for you.

This way switching models would be 2 click action (wit very few options which only make sense to you), currently it's 2 clicks + scroll (and pay attention as some models have very similar names) +2 clicks + scroll (and be carufl) + 2 clicks
