### ISSUE TITLE
"Append to new document" button in the chat adds the selected snippet twice

### ISSUE THREAD

**Issue by kha84** [rjmacarthy/twinny#103]
**Describe the bug**

If you use any of the advanced features of Twinny from the context menu, like "Add types" / "Explain" / "Generate docs" / etc, the code snippets appearing in the chat on the left hand side are having three action buttons:
* Accept 
* Copy code
* Append to new document

First two actions are working fine, but the third one (Append to new document) puts the selected snippet to a new document **twice** - one after another

**To Reproduce**
1. In the VSCode select any code snippet and invoke context menu
2. Select "Twinny - Add types" item and wait for LLM to respond in the left-hand-side chat pannel
3. Choose any code snippet from the chat panel and click "Append to new document" button 

**Expected behavior**
The selected code snippet should be added to the new document just once

**Comment by AntonKrug** [comment]
I think I noticed the issue, provided a PR to fix it

**Comment by rjmacarthy** [comment]
Thanks @AntonKrug for fixing, I merged and released the new version.

**Comment by kha84** [comment]
Love you guys. Thanks a lot! That was damn fast :)
