### ISSUE TITLE
Suggestion: two button state icons for "Toggle selection preview"

### ISSUE THREAD

**Issue by ericvrp** [rjmacarthy/twinny#108]
"Toggle auto scroll on/off" has a unique icon for each state. selection preview should also have two.

<img width="636" alt="image" src="https://github.com/rjmacarthy/twinny/assets/4216292/ad8323f7-05eb-481a-ac55-54a3d22ed720">

<img width="624" alt="image" src="https://github.com/rjmacarthy/twinny/assets/4216292/b249648a-12bd-4aee-883c-4947c780d260">

**Comment by AntonKrug** [comment]
I can look at it

**Comment by AntonKrug** [comment]
Made PR, hopefully this resolves the problem.

**Comment by rjmacarthy** [comment]
Thanks @AntonKrug it's fixed now .

**Comment by ericvrp** [comment]
Yes thank you for the quick fixes!
