### ISSUE TITLE
Suggestion: show top and installed LLM for current api provider

### ISSUE THREAD

**Issue by ericvrp** [rjmacarthy/twinny#109]
When selecting for instance Ollama it would be great to see a few suggestions plus a list of what I have installed already for quick switching.

**Comment by rjmacarthy** [comment]
I added a llm selector option to the latest version.

**Comment by ericvrp** [comment]
cool! having this in the settings as well would be nice.

**Comment by rjmacarthy** [comment]
> cool! having this in the settings as well would be nice.

Unfortunately it's not possible unless the list is statically defined at compile time. This is why I added it to the sidebar at runtime.
