### ISSUE TITLE
Suggestion: "auto" setting for Fim template format in settings

### ISSUE THREAD

**Issue by ericvrp** [rjmacarthy/twinny#110]
I selected deepseek-coder:1.3b-base-q5_K_M as Fim model name and have the feeling that Twinny should be able to detect the Fim template format.

This could be based on the model name but even better would be to have Twinny communicate with the LLM to find out what works best.

**Comment by rjmacarthy** [comment]
I just version `3.5.24` which  now derives the FIM template from the model name.

Thanks for the suggestion.
