### ISSUE TITLE
Code completion not working

### ISSUE THREAD

**Issue by pixelkaiser** [rjmacarthy/twinny#118]
**Describe the bug**
It looks like the code completion is not triggering. I can see requests on the ollama server vor /api/tags and chat requests but nothing is showing for code completion. How can I debug this?

**To Reproduce**
1. Opened a python file
2. Tried to get code suggestions 
3. Pressed Alt+\ to force it to complete
4. No output and no requests on ollama end

**Desktop (please complete the following information):**
 - macOS client and dockerized ollama server on linux
 - forwarded localhost port to ollama server

**Comment by rjmacarthy** [comment]
Please enable debug option in twinny, restart vscode then open developer tools to see what is happening.

Many thanks,

**Comment by pixelkaiser** [comment]
Looks like a restart of vscode did the trick 🤷
