### ISSUE TITLE
Configuration option to Send chat message on Enter

### ISSUE THREAD

**Issue by gerwintmg** [rjmacarthy/twinny#121]
**Is your feature request related to a problem? Please describe.**
When i am chatting with short messages, I'm am used to use [Enter] to send the message, however with twinny i'm forced to return to the mouse to send my message or use the for me unnatural key combo of [Ctrl]+[Enter]

**Describe the solution you'd like**
I would like the chat to send my message when i press enter, and except [schift]+[Enter] to be used for a newline,
Could this be a configuration option? Or am i missing an already existing way to change this?

**Describe alternatives you've considered**
Writing this i wonder if there is an option to change this behavior.

**Additional context**
I am aware that [Ctrl]+[Enter] send the message, it works but is different from what i am used to.

**Comment by rjmacarthy** [comment]
This is something I've been meaning to implement. Thanks for the suggestion.
