### ISSUE TITLE
On demand scroll down

### ISSUE THREAD

**Issue by AntonKrug** [rjmacarthy/twinny#122]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to have auto-scroll off and keep it off, but for a moment (and only once) you want to scroll down.

**Describe the solution you'd like**
 A dedicated button `scroll to bottom` which would scroll down could solve this.

**Describe alternatives you've considered**
Scrolling manually.

**Additional context**
I'm willing to contribute the feature myself, if it's ok to add it.

**Comment by rjmacarthy** [comment]
Hey @AntonKrug sure please go ahead and add the feature if you want. I can check it before any release.

Many thanks
