### ISSUE TITLE
Custom system messages per task type

### ISSUE THREAD

**Issue by curioushuman** [rjmacarthy/twinny#123]
**Is your feature request related to a problem? Please describe.**

When asking LLMs to write tests for me, I've learnt to become more and more specific about what I want (generally in line with the coding standards of my current organisation). This is best added to a system message, so it is included with every request.

However, with a single system template there would be unnecessary noise related to each of the individual contexts (if all contexts had to be included in a single system message) e.g. writing tests, explaining code, writing documentation, etc.

**Describe the solution you'd like**
I've approached it via the simplest method possible for now, and am open to more configurable/friendlier approaches.

Essentially by adding a template in the templates directory that matches the task name the assistant will pick up that system message instead of the default e.g. 

* add-tests.hbs
* add-tests-system.hbs

**Describe alternatives you've considered**
I'll be honest. No alternatives so far.

**Additional context**
Non at this time.

**Comment by curioushuman** [comment]
This is my first time contributing. Apologies for newbie-ness.

I have a local branch with proposed changes. What are the next steps? Do I need permissions?

**Comment by rjmacarthy** [comment]
#124
