### ISSUE TITLE
No tutorial available

### ISSUE THREAD

**Issue by adilsal33m** [rjmacarthy/twinny#13]
Running the ollama server and installing the plugin is not sufficient to start code completion. I am still not able to get it to work on VS Code. A tutorial will be helpful to get started.

**Comment by rjmacarthy** [comment]
To improve the clarity and structure of your message, consider the following revision:

Hello,

To utilize the Ollama API, you need to execute a specific command. Here's the format:

`ollama run <modelname>`

For example, to use the codellama:7b-code model, the command would be:

`ollama run codellama:7b-code '<PRE> def compute_gcd(x, y): <SUF>return result <MID>'`

I've also updated the README with some brief instructions to assist with this process.

This setup should enable you to get the desired completions. If you encounter any issues or have further questions, please feel free to reach out.
