### ISSUE TITLE
Fetch failed when using a remote https URL

### ISSUE THREAD

**Issue by Sinan-Karakaya** [rjmacarthy/twinny#131]
**Describe the bug**
I deployed an Ollama instance accessible through an https url. When trying to use the extension, I get a fetch failed error. I suspect this is because I need to specify a port for an https URL.

**To Reproduce**
1. Have an Ollama instance accessible on an https URL
2. Set the endpoint in the settings
3. Try to chat with the model
5. See error

**Expected behavior**
I should get completions appearing.

**Screenshots**
```
***Twinny Stream Debug***
Streaming response from https://my_url:443.
Request body:
{
  "model": "deepseek-coder:33b-base-q4_K_M",
  "prompt": "<<SYS>>You are a helpful, respectful and honest coding assistant.\nAlways reply with using markdown.\nFor code refactoring, use markdown with code formatting.<</SYS>>\n  \n[INST] how do I write a bubble sort in python\n [/INST]\n  ",
  "stream": true,
  "keep_alive": "5m",
  "options": {
    "temperature": 0.2,
    "num_predict": 1024
  }
}


Request options:
{
  "hostname": "https://my_url",
  "port": 443,
  "path": "/api/generate",
  "protocol": "http",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json",
    "Authorization": "Bearer "
  }
}


    
log.ts:437   ERR [Extension Host] Fetch error: TypeError: fetch failed
	at Object.fetch (node:internal/deps/undici/undici:11576:11)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async e.streamResponse (/Users/username/.vscode/extensions/rjmacarthy.twinny-3.6.5/out/index.js:2:121305)
```
**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.3
 - VSCode Version 1.86.2

**Additionnal Context**
I tried enabling TLS, and with other ports (11434, 80, 443) but no changes in the error

**Comment by AntonKrug** [comment]
Wondering, do you ned to specify the port when it's already given by the https?
Is the HTTPs having a valid certficate which works correctly without any of your local/browser exceptions (or locally installed certificates)?

**Comment by rjmacarthy** [comment]
Hey, it seems that you need to check the use tls option and set the hostname without the https prefix? We have another user who has successfully set this up. @rcgtnick could you please offer any advice?

**Comment by Sinan-Karakaya** [comment]
Thanks for the answers, I will try all your options today and report with the results

**Comment by rcgtnick** [comment]
> Hey, it seems that you need to check the use tls option and set the hostname without the https prefix? We have another user who has successfully set this up. @rcgtnick could you please offer any advice?

Yes, the hostname field is just the hostname, not a URL, so it doesn't accept `protocol://`.

**Comment by rjmacarthy** [comment]
Hmm, 401 means Unauthorized You also need to add your `Bearer` token in the settings for `twinny`.  Also enable debug to see what is going on under the hood and that the Bearer is added properly.  Sometimes a restart is needed for settings to take place properly, it's a bug. 
![image](https://github.com/rjmacarthy/twinny/assets/5537428/e6aa37fd-0024-4933-ac72-ccfd76fba676)

**Comment by Sinan-Karakaya** [comment]
> Hmm, 401 means Unauthorized. You also need to add your `Bearer` token in the settings for `twinny`. Also enable debug to see what is going on under the hood and that the Bearer is added properly. Sometimes a restart is needed for settings to take place properly, it's a bug. ![image](https://private-user-images.githubusercontent.com/5537428/307938310-e6aa37fd-0024-4933-ac72-ccfd76fba676.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjUwMzYsIm5iZiI6MTcwOTAyNDczNiwicGF0aCI6Ii81NTM3NDI4LzMwNzkzODMxMC1lNmFhMzdmZC0wMDI0LTQ5MzMtYWM3Mi1jY2ZkNzZmYmE2NzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMDkwNTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjliZTk1MGZhZjhlNGU5ZDY5MTk0OTE1ZDQ1NTI4ZWUxMTE5NDYyNTUzMjM3M2ZlMzE5ZTgzY2NlM2UxMTM3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bulzuZk0eQgVJYxJ2-Uc5588ByuYSZwpGmL1oi47YzU)

Turns out some extra characters slipped in the Bearer token when I copied it... Entering the right one fixed it (obviously). Closing the issue, thanks for the help :)

**Comment by arttraratatr** [comment]
> Is the HTTPs having a valid certficate which works correctly without any of your local/browser exceptions (or locally installed certificates)?
> 
> The enabling TLS will switch the protocols (so some calls instead of HTTP will use HTTPS), but if the HTTPS is using self signed certificate then that will fail.
> 
> And probably the plugin needs a option to ignore the TLS errors and continue, something in the lines https://stackoverflow.com/a/59944400/4535300
> 
> If that is the case I could try to implement it myself and do the PR, if that is ok

Does self-signed certificate work now? Any updates on this? thx!
