### ISSUE TITLE
Generation gets interrupted

### ISSUE THREAD

**Issue by MAKESEB** [rjmacarthy/twinny#133]
When generating it gets interrupted and stops. 
![CleanShot 2024-02-24 at 15 48 00@2x](https://github.com/rjmacarthy/twinny/assets/113889978/e0eb3ede-9065-4e5c-a5fa-1adfd2b2a5ee)

**Comment by rjmacarthy** [comment]
Please check max token for chat setting and set to `-1` for infinite. The model may be sending eos token or the request from the server was ended.

**Comment by MAKESEB** [comment]
![CleanShot 2024-02-24 at 16 19 14@2x](https://github.com/rjmacarthy/twinny/assets/113889978/88016aed-8d1a-4918-8923-7549d353ea6b)
![CleanShot 2024-02-24 at 16 19 33@2x](https://github.com/rjmacarthy/twinny/assets/113889978/d025d183-8ac1-48f6-8e5f-c99ad0f5e103)
Sadly still ending abruptly. Tested with:
![CleanShot 2024-02-24 at 16 20 15@2x](https://github.com/rjmacarthy/twinny/assets/113889978/77cd7ce6-4601-47fd-bb60-2b04bc788982)

**Comment by rjmacarthy** [comment]
Hmm, not sure will have to check. Does it happen in terminal when calling Ollama with the same options? You can enable debug modem in settings to see the request and options.

**Comment by rjmacarthy** [comment]
Hey @MAKESEB I updated in 3.7.0 to the new version of the Ollama API which supports Open AI specification, it may help with this issue, please report back.

**Comment by Smrkc** [comment]
Updating twinny and setting all token limits to -1 solves the incompletion issue for me. Thanks

**Comment by rjmacarthy** [comment]
Thanks!
