### ISSUE TITLE
Generate commit message with git diff

### ISSUE THREAD

**Issue by kv-gits** [rjmacarthy/twinny#134]
**Is your feature request related to a problem? Please describe.**
I use this command to generate commit message with LLM
... -p "[INST] Write code to solve the following coding problem that obeys the constraints and passes the example test cases:\n Compose a brief description of the git commit for the following changes.\n $(git diff HEAD^ HEAD) \n Commit brief is: [/INST]"
also as an option
git diff --cached
**Describe the solution you'd like**
Would like to make such commit message for current changes with twinny button

**Comment by rjmacarthy** [comment]
Hey, I've just added this in `3.10.8`!

https://github.com/rjmacarthy/twinny/pull/196

**Comment by rjmacarthy** [comment]
This is now done.
