### ISSUE TITLE
Errors when auto-suggestion in repository with github comments and changes

### ISSUE THREAD

**Issue by son1ss** [rjmacarthy/twinny#136]
**Describe the bug**
Twinny errors when there are comments and uncommited changes in same file in repository, I assume it tries to find nonexistent files

**To Reproduce**
1. Go to any file with comments on github and create any changes
2. Try to force auto suggestion
3. See the logs in devtools

**Expected behavior**
Expected to work as usual

**Logs**
```
ERR cannot open file:///commit~4b614e95/src/components/modal/modal.tsx. Detail: Unable to read file '\commit~4b614e95\src\components\modal\modal.tsx' (Error: Unable to resolve nonexistent file '\commit~4b614e95\src\components\modal\modal.tsx'): CodeExpectedError: cannot open file:///commit~4b614e95/src/components/modal/modal.tsx. Detail: Unable to read file '\commit~4b614e95\src\components\modal\modal.tsx' (Error: Unable to resolve nonexistent file '\commit~4b614e95\src\components\modal\modal.tsx')
    at r.$tryOpenDocument (vscode-file://vscode-app/c:/Users/fomin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2197:62910)
```

**Desktop (please complete the following information):**
 - OS: Windows
 - VS Code
 - Latest version

**Additional context**

**Comment by rjmacarthy** [comment]
Hey, sorry I am confused about how to replicate it.  What do you mean `Go to any file with comments on github and create any changes`?  Can you share a video or some more replication steps, please?  Thanks.

**Comment by rjmacarthy** [comment]
Hi @son1ss please could you test it now, I added some code changes recently.

**Comment by rjmacarthy** [comment]
Stale
