### ISSUE TITLE
Bad/no suggestions in chat and FIM

### ISSUE THREAD

**Issue by Sinan-Karakaya** [rjmacarthy/twinny#137]
**Describe the bug**
In chat, asking a simple question will make it answer by including [INST] tags and other unrelated answers.
In FIM, it will get no suggestions, or incorrect suggestions. (Such as suggesting a <PRE/> tag for a python function ?)

**To Reproduce**
1. Get a deepseek-coder:33b-base-q4_K_M running for both FIM and chat
2. Write a quicksort function definition and wait for the completion, or just ask something simple such as writing a for loop in python
3. See the bad suggestions happen

**Expected behavior**
I should get well formatted suggestions, with correct answers. (Tested with the same model with Llama-coder and would get faster and correct suggestions)

**Screenshots**
![Capture d’écran 2024-02-27 à 10 34 49](https://github.com/rjmacarthy/twinny/assets/91690021/f0c5d16f-00cd-4ced-b8df-c0146ca32580)
![Capture d’écran 2024-02-27 à 10 35 35](https://github.com/rjmacarthy/twinny/assets/91690021/292f13a0-e67e-4fac-8266-741a9519cd3e)

**Desktop (please complete the following information):**
 - OS: MacOS M1
 - Version latest

**Comment by rjmacarthy** [comment]
Hey, if you're using deepseek coder for chat you need to update the prompt template, it's got the llama special tokens i.e `[INST]` in the prompt.  I am not sure what it should be for deepseek.  In terms of the FIM, the base model should work.  Please enable debug and post the results, thanks.

**Comment by Sinan-Karakaya** [comment]
I couldn't find what the equivalent was for deepseek unfortunately.
As for the FIM, no special output or logs were displayed during the completion.

**Comment by rjmacarthy** [comment]
Hey, I tested `deepseek-coder:33b-base-q4_K_M` it was working for FIM for me.  Maybe try to use a smaller model for FIM?  As you mention it does not work for instruct, and it's a known issue due to the prompt template, would recommend a llama instruct model for chat.

**Comment by Sinan-Karakaya** [comment]
Hi there, thanks for the reply. I'll reply back when I'll be done testing by the end of the week hopefully.

**Comment by rjmacarthy** [comment]
Stale
