### ISSUE TITLE
Change Keyboard shortcut for manual triggering of FIM

### ISSUE THREAD

**Issue by mtoniott** [rjmacarthy/twinny#145]
Manual triggering of the FIM model is necessary to save battery when on a laptop. But the current keyboard shortcut is difficult to use if you don't have an english keyboard layout (e.g. if you have a french layout). 

Sorry if I'm wrong, but I don't see any way to change this keyboard shortcut.

Have a good day and thank you for this piece of software.

**Comment by brunoais** [comment]
You can change in the keyboard shortcuts screen. See:
![image](https://github.com/rjmacarthy/twinny/assets/639467/4e3d47ea-225e-4279-8c74-d66844d35ea9)
![image](https://github.com/rjmacarthy/twinny/assets/639467/921cc5c2-bcc4-4118-afbb-4b7684750946)

**Comment by rjmacarthy** [comment]
This is already possible, so closing.

**Comment by mtoniott** [comment]
Sorry to rebump this, but what keyboard shortcut do we need to edit ? None seem to fit, hence the issue.

Sorry for the annoyance.

**Comment by brunoais** [comment]
@mtoniott AFAIK, you can only enable or disable it

**Comment by Jaizkibel42** [comment]
I can't see how to change the shortcut for FIM.
But this would be really useful.

Example:
I am on a MacBook with german keyboard. I need to the combination SHIFT+ALT+7 to get a '\'
No idea how to produce a ALT+\ at all.

**Comment by mtoniott** [comment]
I don't understand why this issue is closed. It is not implemented.

**Comment by Jaizkibel42** [comment]
Hi @mtoniott,

I have found a solution. You can define a shortcut for "editor.action.inlineSuggest.trigger"
This triggers Twinny FIM completion.
