### ISSUE TITLE
Chat only gives one answer, then it does not respond

### ISSUE THREAD

**Issue by piulin** [rjmacarthy/twinny#150]
**Describe the bug**
When using the chat, the first interaction is answered as normal, but further interaction is not possible because it won't respond.

**To Reproduce**

1. Open chat
2. Start a convesation
3. Wait for response
4. Try to continue conversation

**Expected behavior**

The chat system should be able to continue the conversation

**Screenshots**

![image](https://github.com/rjmacarthy/twinny/assets/12646374/423aea78-cab8-472d-ac21-051b715ab322)

**Desktop (please complete the following information):**
 - OS: Debian

**Additional context**
Using twinny from vscode extension manager:
Published
2023-08-25, 09:49:54
Last released
2024-02-29, 20:41:00
Last updated
2024-03-01, 08:23:50

**Comment by rjmacarthy** [comment]
Please could you share the twinny debug output? You can find it in developer tools of vs code. Thanks.

**Comment by piulin** [comment]
Just saw that vllm responded with status 400 but can't see the request.

```js
ERR [Extension Host] Fetch error: Error: Server responded with status code: 400
    at e.streamResponse (/home/tecnalia/.vscode/extensions/rjmacarthy.twinny-3.7.7/out/index.js:2:121658)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
console.ts:137 [Extension Host] Fetch error: Error: Server responded with status code: 400
    at e.streamResponse (/home/tecnalia/.vscode/extensions/rjmacarthy.twinny-3.7.7/out/index.js:2:121658)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Interestingly enough using the template settings buttons, such as "Explain" work as expected.

**Comment by rjmacarthy** [comment]
I guess that vLLM is not fully compatible with twinny? You need to provide the debug output of twinny, tick the debug option in settings. Thanks.

**Comment by piulin** [comment]
> I guess that vLLM is not fully compatible with twinny? You need to provide the debug output of twinny, tick the debug option in settings. You may need to restart vscode for the setting to take effect. Thanks.

I think so. Request
```typescript
[Extension Host] 
***Twinny Stream Debug***
Streaming response from <redacted>
Request body:
{
  "model": "TheBloke/deepseek-coder-33B-instruct-GPTQ",
  "prompt": "[INST] hello\n [/INST]\nHello！How can I assist you with your programming or computer science related questions today?\n\n[INST] ko\n [/INST]\n  ",
  "stream": true,
  "max_tokens": 512,
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful, respectful and honest coding assistant.\nAlways reply with using markdown.\nFor code refactoring, use markdown with code formatting.\n  "
    },
    {
      "role": "user",
      "content": "hello",
      "type": ""
    },
    {
      "role": "assistant",
      "content": "Hello！How can I assist you with your programming or computer science related questions today?\n",
      "type": "",
      "language": {
        "languageId": "markdown"
      }
    },
    {
      "role": "user",
      "content": "ko",
      "type": "chat"
    }
  ],
  "temperature": 0.2
}


Request options:
{
  "hostname": "<redacted>",
  "port": 8005,
  "path": "/v1/chat/completions",
  "protocol": "http",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json",
    "Authorization": "Bearer EMPTY"
  }
}
```
Vllm response:
```json
{
	"object": "error",
	"message": "[{'type': 'string_type', 'loc': ('body', 'messages', 'str'), 'msg': 'Input should be a valid string', 'input': [{'role': 'system', 'content': 'You are a helpful, respectful and honest coding assistant.\\nAlways reply with using markdown.\\nFor code refactoring, use markdown with code formatting.\\n  '}, {'role': 'user', 'content': 'hello', 'type': ''}, {'role': 'assistant', 'content': 'Hello！How can I assist you with your programming or computer science related questions today?\\n', 'type': '', 'language': {'languageId': 'markdown'}}, {'role': 'user', 'content': 'ko', 'type': 'chat'}], 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}, {'type': 'string_type', 'loc': ('body', 'messages', 'list[dict[str,str]]', 2, 'language'), 'msg': 'Input should be a valid string', 'input': {'languageId': 'markdown'}, 'url': 'https://errors.pydantic.dev/2.5/v/string_type'}]",
	"type": "BadRequestError",
	"param": null,
	"code": 400
}
```

**Comment by rjmacarthy** [comment]
Thanks it seems like expecting `msg` but twinny sending OpenAI compatible data and it's `role` and `content`.  Not sure about vLLM it's not fully supported.  We an open issue already for it so will mark this as duplicate. https://github.com/rjmacarthy/twinny/issues/40

**Comment by piulin** [comment]
It turns out that the error comes from sending the key `"language"`, which is not part of the official [OpenAI API](https://platform.openai.com/docs/api-reference/chat/create) for the endpoint `chat/completions/`.
