### ISSUE TITLE
Multi line completion doesn't show completion in editor

### ISSUE THREAD

**Issue by TheLapinMalin** [rjmacarthy/twinny#154]
**Describe the bug**

**To Reproduce**
1. Enable Multi line completion
2. Wait for model
3. Model returns completion response, but response isn't displayed in editor.

**Expected behavior**
Response is displayed in editor.

**Screenshots**
With multi-line enabled:
![image](https://github.com/rjmacarthy/twinny/assets/111463204/3a4a883a-8ada-49e3-b015-185f72a103ca)

With multi-line disabled:
![image](https://github.com/rjmacarthy/twinny/assets/111463204/b1621744-1aec-47ae-885a-200fe0ae47e6)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by rjmacarthy** [comment]
Hello, thanks for the report. I have been using it fine with multiple lines too. I'd have to look into it with your specific model.

**Comment by TheLapinMalin** [comment]
> Hello, thanks for the report. I have been using it fine with multiple lines too. I'd have to look into it with your specific model.

I'm running deepseek-coder-6.7b-instruct.Q5_K_M with KoboldCPP.

Let me know if you'd like more logs out of the model to help debug this.

**Comment by rjmacarthy** [comment]
Stale
