### ISSUE TITLE
The prompt is often malformed with minimal prefix leading to bad generations

### ISSUE THREAD

**Issue by pacman100** [rjmacarthy/twinny#158]
**Describe the bug**
The prompt is often malformed with minimal prefix leading to bad generations.

**To Reproduce**
Example given below wherein the suffix is 25 lines but prefix is 4 lines other than the language type and related info. This leads to bad generations as the prefix needs to be equal weightage.

![Screenshot 2024-03-04 at 1 18 21 PM](https://github.com/rjmacarthy/twinny/assets/13534540/64c2a6aa-dd53-49d2-ae49-c0b35c51ef37)

**Expected behavior**
30 lines of prefix and 30 lines of suffix to be given as prompt. Equal weightage to both prefix and suffix.

**Comment by pacman100** [comment]
For time-being increasing the Context Length to 100 seems to be helping to some extent but still the prefix is way less compared to suffix.

**Comment by pacman100** [comment]
In twinny, the prefix ratio is default to 15% while suffix ratio is at 85%. This has to be the reverse. 

See the reverse engg of the copilot plugin https://thakkarparth007.github.io/copilot-explorer/posts/copilot-internals#what-does-a-prompt-look-like wherein the suffix percentage is default at 15%.

<img width="1074" alt="Screenshot 2024-03-04 at 1 37 47 PM" src="https://github.com/rjmacarthy/twinny/assets/13534540/0cc49d0a-5061-481e-bc99-341f68006afb">

**Comment by pacman100** [comment]
With the above PR fix, the completions are as expected, running the extension from `vsce package` command with the above change:

![Screenshot 2024-03-04 at 2 03 26 PM](https://github.com/rjmacarthy/twinny/assets/13534540/91c02b78-e9e0-4f0e-80f8-3b1e0233e9f6)

**Comment by rjmacarthy** [comment]
Hey @pacman100 thanks for this, it was a silly mistake on my part.  I just merged your PR and released the new version.  Many thanks.

**Comment by pacman100** [comment]
Thank you @rjmacarthy! Twinny is a great open source project, thank you for all the work! ✨
