### ISSUE TITLE
Use two Ollama Server, one for Chat and one for Fim, to improve Twinny Performance

### ISSUE THREAD

**Issue by sthufnagl** [rjmacarthy/twinny#163]
Hi,
this is my first feature request...sorry for the unusual format of the request.  Next time I will improve the feature request!
:-)

**Situation:**
I have two separate Ollama Server that I can use for the great Twinny VS Code Extenstion.
It would be good for the Twinny Performance to use them.

**Request:**
Would it be possible to use two separate Ollama Server, one for Chat and one for Fim?
We have in the Twinny Settings the possibility to choose two different Ollama Models. Why not include the Ollama URL?

**Helping Hand:**
I have some experience with JS/TS.  Where should we change the code to use different Ollama URL? It shouldn't be so complicated to implement it.

Thx in advande

Steve

**Comment by sthufnagl** [comment]
Hi @rjmacarthy,
thanks for your encouraging words. 

- Wouldn't it be  better to "fork" your repo? Instead of a PR? (more isolation?)
- Knowledge of JS/TS isn't enough...I also have to start with VS Code Extensions :-)

Thx

Steve

**Comment by rjmacarthy** [comment]
No worries @sthufnagl , let's reopen it anyway because it's a good suggestion and we can implement it in a future release.

**Comment by AntonKrug** [comment]
I'm wondering if I would have enough knowledge to attempt this one.

**Comment by rjmacarthy** [comment]
This is now ready.
