### ISSUE TITLE
Twinny stops working after machine goes in standby

### ISSUE THREAD

**Issue by onel** [rjmacarthy/twinny#166]
**Describe the bug**
Not sure if this is twinny or an ollama issue but the chat feature seems to stop working after the machine goes in stand by.
Using M1 mac air
Ventura 13.4

**To Reproduce**
1. Start ollama with `ollama run ...`
2. VS code + twinny running normally
4. Close the laptop lid
5. Open back up
6. ollama is still responsive if using the terminal
7. Sending a message through twinny in VS code shows the loading indicator indefinitely

**Expected behavior**
Twinny chat should continue working

Restarting VS code, ollama doesn't seem to fix the problem so I'm wondering if it's also something else.
Ollama works ok through the CLI

**Comment by rjmacarthy** [comment]
Stale
