### ISSUE TITLE
Display an indicator when twinny looses connection the LLM provider

### ISSUE THREAD

**Issue by onel** [rjmacarthy/twinny#168]
**Is your feature request related to a problem? Please describe.**
When twinny looses connection there is no indicator that this thing happened, we just see the loading indicator.

**Describe the solution you'd like**
A warning/error message above the chat box would be helpful to alert the user that something happened.

Not sure how it would look if the side panel is closed and the user just uses FIM

**Comment by rjmacarthy** [comment]
How would you propose that we check that a connection is lost?  I am not a fan of polling the endpoints.

Many thanks,

**Comment by AntonKrug** [comment]
I think there is no connection to provider to begin with? Each API call starts and ends, there is no long going websocket or other connection, there is no way to tell if there is something to respond until the call is made. The plugin would have to be pinging the API all the time just to know its presence. Kinda like on a roadtrip with kids `are we there yet`?

**Comment by onel** [comment]
No, definitely polling would not be a nice option and I'm not sure we need a service to keep track of that.
I was wondering if it makes sense to handle when actual requests fail.

For example, going through the code I see that in `streamTemplateCompletion` twinny makes a POST call with `this._view?.webview.postMessag({})` on top of other calls like `buildStreamRequest`.
I wonder if it makes sense to handle those when they fail, if they fail when ollama is offline?

**Comment by rjmacarthy** [comment]
Not relevant so closing.
