### ISSUE TITLE
Fetch error: Error: Server responded with status code: 404

### ISSUE THREAD

**Issue by JianJroh** [rjmacarthy/twinny#173]
**Describe the bug**

VS code extension features not work, but terminal chat work.

![image](https://github.com/rjmacarthy/twinny/assets/45714701/7067004e-a841-4319-bf63-a00600ccae77)

 Throw `Fetch error: Error: Server responded with status code: 404` in Developer Tools `Console` tab

![image](https://github.com/rjmacarthy/twinny/assets/45714701/284c08eb-6a5a-4484-87af-e13d8e374edc)

`ollama run codellama:7b` in powershell.

![image](https://github.com/rjmacarthy/twinny/assets/45714701/48f00952-eb6f-4d6e-b8fa-c367253c0694)

http://localhost:11434 -> response ```Ollama is running```

**Comment by rjmacarthy** [comment]
Hey, I'm not sure...looks right configuration. Can you call Ollama server with curl?

**Comment by MoXiaoluo** [comment]
any suggestions for this issue? @rjmacarthy

**Comment by MoXiaoluo** [comment]
@JianJroh how to fix this problem?

**Comment by jibinghu** [comment]
is the issue solved?
