### ISSUE TITLE
Default ollama `Chat Api Path` points to the wrong URL path

### ISSUE THREAD

**Issue by brunoais** [rjmacarthy/twinny#191]
**Describe the bug**
Default `Chat Api Path` when setting the `Api Provider` to `ollama`, sets `Chat Api Path` to `/v1/chat/completions` instead of the correct `/api/chat` [(source)](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-chat-completion)

**Note:** This seems to be some sort of copy/paste error or selection error because `/v1/chat/completions` is also the default for `lmstudio` 

**To Reproduce**
1. Go to twinny setting `twinny.apiProvider`
2. Click on it and change to `ollama` (if it's already `ollama`, change to another and change back)
3. Problem: Setting `twinny.chatApiPath` becomes `/v1/chat/completions`. Should have been [`/api/chat`](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-chat-completion).

**Screenshots**
![image](https://github.com/rjmacarthy/twinny/assets/639467/c6f74f29-edeb-48b2-997a-615fd87eb5b4)
![image](https://github.com/rjmacarthy/twinny/assets/639467/de178cf0-6a53-4385-b65c-9a5531c70421)

**Comment by rjmacarthy** [comment]
This was updated as Ollama now support OpenAI specifictaion.

**Comment by brunoais** [comment]
Updating ollama fixed. ollama was outdated.
