### ISSUE TITLE
Cannot chat successfully with ollama

### ISSUE THREAD

**Issue by brunoais** [rjmacarthy/twinny#192]
## **Describe the bug**
No matter what I try to chat with ollama, I get `Sorry, I don’t understand. Please try again.`

When I use `ollama run` with the same model, it works as expected.
I'm using `codellama:7b-instruct` in both cases.

**For clarification:** FIM is working as expected.

## **To Reproduce**
1. Try to chat with bot
2. Get error response

## **Expected behavior**
Chatting with the bot succeeds

## **Screenshots**
![image](https://github.com/rjmacarthy/twinny/assets/639467/24012b06-da01-4adb-9da6-36bfebf7ad6d)
![image](https://github.com/rjmacarthy/twinny/assets/639467/a3f4f31c-3a99-4a97-9376-fe444ca3e2ce)
![image](https://github.com/rjmacarthy/twinny/assets/639467/a619d695-6312-4d5e-b1f4-29666d606731)
![image](https://github.com/rjmacarthy/twinny/assets/639467/994ee207-5fa5-48eb-ad5f-4254018eb917)

## **Desktop (please complete the following information):**
N/A

## **Additional context**

I'm using the default system message provided by twinny. I also tried blanking the template and trying again but made no difference.
Twinny 2.X was working but I have no means to downgrade the version. At least, not in the UI.

See also: #191 because the cause can be related, just invisible to the user

**Comment by rjmacarthy** [comment]
Hey, this was updated as Ollama now support OpenAI specifictaion.

https://ollama.com/blog/openai-compatibility

Please update Ollama and try again.

**Comment by brunoais** [comment]
Updating ollama fixed. ollama was outdated.
