### ISSUE TITLE
No robot icon, no completion

### ISSUE THREAD

**Issue by jjlee** [rjmacarthy/twinny#194]
**Describe the bug**

**To Reproduce**
1. ollama serve
2. ollama run deepseek-coder:base
3. sudo pacman -S vscodium
4. vscodium
3. Go to extensions view, search for twinny, click Install
5. Press Control-Shift-T

**Expected behavior**

The install docs in the README.md of this repo say "You should see the 🤖 icon indicating that twinny is ready to use."

**Actual behaviour**

No robot icon is shown (where is it intended to show up?)

Your screencast doesn't appear to show any 🤖 emoji icon.  Perhaps it's no longer expected?

Alt-backslash to complete didn't seem to do anything in a pane containing python code.  In twinny's settings, I see "This extension is enabled globally.", and "Twinny: Enabled", but lacking the icon the docs say should be there I didn't try very hard.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - twinny Version: v3.10.6

**Comment by jjlee** [comment]
From Show Logs -> Extension Host, the only thing at all relevant-looking I see is:

```
2024-03-30 00:02:09.392 [info] ExtensionService#_doActivateExtension rjmacarthy.twinny, startup: false, activationEvent: 'onStartupFinished'
```

I'm basically new to VS code, so if I can do something else obvious to investigate, tips are appreciated :-)

**Comment by jjlee** [comment]
Trying again today (with no obvious changes in what I'm doing): Alt-\ completion works!

For any others reading: the robot emoji is supposed to show up at the bottom right of the VS code window.  The way my VS code is set up at least, it's not in colour, just monochrome, which is probably why I was missing it.

**Comment by rjmacarthy** [comment]
Sometimes a restart of vscode can help. Thanks.
