### ISSUE TITLE
Possibly my mistake, but I keep getting this error

### ISSUE THREAD

**Issue by russsavagedentsu** [rjmacarthy/twinny#198]
**Describe the bug**
I am connecting to a local LM Studio instance running the API. I know this works because the Twinny chat completion is working. 

But when I try code completion I get this error in LMStudio: 

<img width="487" alt="image" src="https://github.com/rjmacarthy/twinny/assets/146464291/92eb4ff2-53eb-483c-9fb2-bf035198fdbe">

Do I have to set the prompt in twinny myself? In LMStudio? Thanks for help with a noob problem.

**Expected behavior**
Code completion

**Comment by rjmacarthy** [comment]
Hello @russsavagedentsu, it was my fault, I broke it in previous release.  I just pushed a fix in `3.10.11`.  Please could you let me know how you get on, I have tested it and it works.

Many thanks

**Comment by russsavagedentsu** [comment]
No worries, thanks!
