### ISSUE TITLE
When using the vscode twinny plugin with remote-ssh for remote development, code suggestions are not working. 

### ISSUE THREAD

**Issue by 0x0101010** [rjmacarthy/twinny#207]
Describe the bug
When using the vscode twinny plugin with remote-ssh for remote development, code suggestions are not working. However, code suggestions work fine when working locally. chat 

To Reproduce

Open Visual Studio Code.
Install the Twinny plugin.
Connect to a remote server using the remote-ssh extension.
Open a file for editing on the remote server.
Start typing and try to get code suggestions.
Notice that code suggestions are not appearing.
Expected behavior
Code suggestions should appear while typing, regardless of whether working locally or remotely.

Desktop

OS: [e.g. Windows 11]

Vscode:1.88.0 

twinny: v3.11.3

Additional context
Apart from the issue with code suggestions in the Twinny plugin and remote-ssh, all other functionalities in Visual Studio Code seem to be working fine. I can still chat and interact with the editor without any problems. The issue seems to be isolated to the code suggestion feature when working with remote development.

**Comment by marctrem** [comment]
<img width="1160" alt="image" src="https://github.com/rjmacarthy/twinny/assets/1619947/147d6d8d-bed7-4421-a7c4-0df75e07ad70">


Looks like the plugin is attempting to contact a server that's local to your editor for completion.
You can:
- run ollama locally
- setup port forwarding (so your remote ollama is accessible locally)
- point twinny to your remote ollama (possibly insecure)

**Comment by rjmacarthy** [comment]
Hey, thanks for reporting.  

Please help me understand correctly. The chat works but not the auto-complete?  Or nothing at all?

**Comment by rjmacarthy** [comment]
Stale

**Comment by zikeji** [comment]
I'm also running into this issue.

This is the specific error I'm seeing:

```
  ERR cannot open vscode-remote://ssh-remote%2Bdev-vm/embeded.embeddedhtml. Detail: Unable to read file 'vscode-remote://ssh-remote+dev-vm/embeded.embeddedhtml' (Error: Unable to resolve nonexistent file 'vscode-remote://ssh-remote+dev-vm/embeded.embeddedhtml'): CodeExpectedError: cannot open vscode-remote://ssh-remote%2Bdev-vm/embeded.embeddedhtml. Detail: Unable to read file 'vscode-remote://ssh-remote+dev-vm/embeded.embeddedhtml' (Error: Unable to resolve nonexistent file 'vscode-remote://ssh-remote+dev-vm/embeded.embeddedhtml')
    at n.$tryOpenDocument (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2195:62578)
```

Which I can't make heads or tales of. My "workaround" is to use Llama Coder for completions and Twinny for chat.

**Comment by phyzical** [comment]
can confirm if a provide is using remote ssh i get 

```
  ERR cannot open file:///embeded.embeddedhtml. Detail: Unable to read file '/embeded.embeddedhtml' (Error: Unable to resolve nonexistent file '/embeded.embeddedhtml'): CodeExpectedError: cannot open file:///embeded.embeddedhtml. Detail: Unable to read file '/embeded.embeddedhtml' (Error: Unable to resolve nonexistent file '/embeded.embeddedhtml')
    at OFe.$tryOpenDocument (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:615:8481)
```
