### ISSUE TITLE
VSCodium reports as it is not compatible with VS Code '1.81.1'.

### ISSUE THREAD

**Issue by marcusgreen** [rjmacarthy/twinny#209]
**Describe the bug**
Works wonderfully with VSCode but cannoot install with VSCodum. 
Greetings from (old) York.

**To Reproduce**
1. Download from https://marketplace.visualstudio.com/items?itemName=rjmacarthy.twinny
2.From the command line run  ``codium --install-extension rjmacarthy.twinny-3.11.4.vsix ``

Installing extensions...
(node:1112329) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `codium --trace-deprecation ...` to show where the warning was created)
Error: Unable to install extension 'rjmacarthy.twinny' as it is not compatible with VS Code '1.81.1'.
    at U.install (/usr/share/codium/resources/app/out/vs/code/node/cliProcessMain.js:50:6422)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async y.installVSIX (/usr/share/codium/resources/app/out/vs/code/node/cliProcessMain.js:28:363)
    at async /usr/share/codium/resources/app/out/vs/code/node/cliProcessMain.js:27:19337
    at async Promise.all (index 0)
    at async y.installExtensions (/usr/share/codium/resources/app/out/vs/code/node/cliProcessMain.js:27:19266)
    at async /usr/share/codium/resources/app/out/vs/code/node/cliProcessMain.js:50:33025
    at async Object.ge [as main] (/usr/share/codium/resources/app/out/vs/code/node/cliProcessMain.js:50:38084)
    at async v (/usr/share/codium/resources/app/out/vs/code/node/cli.js:14:26808)
Failed Installing Extensions: file:///home/marcusgreen/Downloads/rjmacarthy.twinny-3.11.4.vsix

**Expected behavior**
Installation

Screen shot is output from when attempting to install from within VSCodium.

![twinny_error](https://github.com/rjmacarthy/twinny/assets/732202/23e0719c-2ef8-4015-84f9-ccadb7f83e53)

**Comment by rjmacarthy** [comment]
Hey, I am able to install with latest VSCodium through the built in extension market place there, are all of your version numbers including `codium` cli up to date?

**Comment by marcusgreen** [comment]
My apologies, my vscodium was not up to date (I had installed via snap). I have now installed using the deb and it is the right version and explaining my own code to me. Sorry for wasting your time, and thank you for this fabulous plugin.
