### ISSUE TITLE
Twinny for Visual Studio Community 2022

### ISSUE THREAD

**Issue by schwaben-github** [rjmacarthy/twinny#210]
Hi,

the concept of having a locally installed open source Copilot was very exciting for me, but I couldn't find Twinny extension for Visual Studio Community 2022.

As far as I understand, there is no possibility of using it on VS. Is it planned to offer this functionality?

Thanks in advance for your kind answer!

**Comment by rjmacarthy** [comment]
Hey, thanks for the question.  

Unfortunately there are no plans to add the extension for Visual Studio Community 2022. AFAIK the implementation details are widely different and I do not own a copy of Windows which makes it impossible for me to develop it.  

All the best and many thanks.
