### ISSUE TITLE
Not showing all model after update to latest version

### ISSUE THREAD

**Issue by askareija** [rjmacarthy/twinny#216]
**Describe the bug**
After update twinny doesn't show all my model.

twinny before update:
![gambar](https://github.com/rjmacarthy/twinny/assets/21377617/ed109afe-a368-47af-8779-f6cbaffe0733)

Twinny after update:
![gambar](https://github.com/rjmacarthy/twinny/assets/21377617/75a3fc3c-0503-4b18-9888-44dc3c9f91d0)

**Expected behavior**
Twinny is showing all model. Actually previous version is working, but after i updated to latest version it's not working.

**Desktop**
 - OS: EndeavourOS (Arch Linux)
 - Twinny version v3.11.14

**Comment by orkutmuratyilmaz** [comment]
Same here, with Manjaro Linux.

**Comment by rjmacarthy** [comment]
Hello, the model select and provider manager was updated in this release. 

https://github.com/rjmacarthy/twinny/releases/tag/v3.11.0

Different providers/models can now be set here without opening the settings menu everytime.

Hope that helps.

**Comment by askareija** [comment]
i'm using ollama and only ollama that doesn't have model name field.

ollama:
![gambar](https://github.com/rjmacarthy/twinny/assets/21377617/f7c2e541-e742-4988-9001-ff525f41e5cb)

llamacpp/other provider:
![gambar](https://github.com/rjmacarthy/twinny/assets/21377617/a17c06d6-64c7-4b81-8c85-0e22a2a38420)

also i don't know the API path for ollama, i've tried `/api/chat`, using llamacpp but it return 400 and twinny become endless loading.

![gambar](https://github.com/rjmacarthy/twinny/assets/21377617/dd8692ed-f105-48e5-aa7b-10924592db31)

![gambar](https://github.com/rjmacarthy/twinny/assets/21377617/e833fe97-90ff-4aad-944f-a3b4aa691bab)

![gambar](https://github.com/rjmacarthy/twinny/assets/21377617/e51c16b3-3aa5-4f8c-8fa1-1bba7bbcc8ff)


now i'm using latest version 3.11.19

**Comment by rjmacarthy** [comment]
Hello, please make sure that your Ollama settings in the extension settings are correct i.e hostname and port.  

![image](https://github.com/rjmacarthy/twinny/assets/5537428/f97b1c85-dfe6-426f-aa64-98db5129f85c)

In the provider config the model dropdown is populated based on `api/tags` from Ollama api. For other providers I am lazy and just put a text box there.

I will make it more clear for future release.  The endpoint for Ollama should be `/v1/chat/completions`.

Hope it helps,

**Comment by askareija** [comment]
okay it's working thanks. But if i'm using dev container, i have to change this host to `host.docker.internal`, and if i'm using local host is `localhost`. a little bit complicated. looks like my workaround was create 2 providers with the same model name, but only hostname is different.

![gambar](https://github.com/rjmacarthy/twinny/assets/21377617/52d51828-3f82-46f8-b34e-6a03a1f3b252)

![gambar](https://github.com/rjmacarthy/twinny/assets/21377617/fc1f1fa1-c427-40ce-b6c7-485bdebd3d03)

**Comment by rjmacarthy** [comment]
Everyone has different setup, I just made it so it can be flexible for everyone, some more complicated than others.

Many thanks!

**Comment by askareija** [comment]
thank you, last question, i'm using stable-code for FIM, but it's always return 400, is there anything wrong?

![gambar](https://github.com/rjmacarthy/twinny/assets/21377617/eebe842c-cc18-400e-b726-0b6bae142ec9)

![gambar](https://github.com/rjmacarthy/twinny/assets/21377617/b7043678-ba55-40c7-9999-ccbd4f4c75b8)

**Comment by askareija** [comment]
> thank you, last question, i'm using stable-code for FIM, but it's always return 400, is there anything wrong?
> 
> ![gambar](https://private-user-images.githubusercontent.com/21377617/324777458-eebe842c-cc18-400e-b726-0b6bae142ec9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjUwNzMsIm5iZiI6MTcxMzg2NDc3MywicGF0aCI6Ii8yMTM3NzYxNy8zMjQ3Nzc0NTgtZWViZTg0MmMtY2MxOC00MDBlLWI3MjYtMGI2YmFlMTQyZWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA5MzI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMTRjM2U4OGU3NDBhNGE2NDhhMDFiYTEyMDQ0MjE0NmExMGMyZGY4MmZlNmZiZjYzMjZiYzc3NDcwZWRhMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dvZjrs97xeJHCtx_KR-tyeiDS0Huaw_GAXaB_g5e84c)
> 
> ![gambar](https://private-user-images.githubusercontent.com/21377617/324777639-b7043678-ba55-40c7-9999-ccbd4f4c75b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjUwNzMsIm5iZiI6MTcxMzg2NDc3MywicGF0aCI6Ii8yMTM3NzYxNy8zMjQ3Nzc2MzktYjcwNDM2NzgtYmE1NS00MGM3LTk5OTktY2NiZDRmNGM3NWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA5MzI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YjJhYjZjODM3YzcwNzU3NmFlYjU2NDRmMWQ1MGYxYTM0MTUwYWY1Yjg3NWNkMGI2Yjk3ZjY2ZGI1NTZlNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3-N0DERbWGES30TJdRjID9yVyFE8scDB0fC-YRO2sVM)

nevermid, looks like the API path for FIM is `/api/generate`
