### ISSUE TITLE
Extension does not load at all after update to v3.11.18

### ISSUE THREAD

**Issue by mdbooth** [rjmacarthy/twinny#218]
**Describe the bug**
Running v3.11.17 I have 2 visual elements relating to Twinny:

The twins are in the 'extensions bar' on the left:
![image](https://github.com/rjmacarthy/twinny/assets/1318691/beb28331-4840-4b73-9836-a38c714c1f8a)

The robot is in the status bar:
![image](https://github.com/rjmacarthy/twinny/assets/1318691/bf700486-f301-4f62-938a-e2481cb28eb8)

When updating to v3.11.18 and reloading the VSCode window, neither of these visual elements are present, and code completions do not function.

When downgrading to v3.11.17 everything works as expected again.

**Desktop (please complete the following information):**
 - OS: Windows11 (WSL2)

**Comment by rjmacarthy** [comment]
Hey, I am not having this issue, are any error in your dev console for vscode? Help -> Toggle Developer Tools.

Many thanks,

**Comment by mdbooth** [comment]
And now it loads! No explanation for that, but I'm not going to dwell on it. Thanks!
