### ISSUE TITLE
Type error fetch failed t.streamResponse

### ISSUE THREAD

**Issue by FrozzDay** [rjmacarthy/twinny#221]
**Describe the bug**
i got this when trying openai compatible api with twinny 
```
Fetch error: TypeError: fetch failed
	at Object.fetch (node:internal/deps/undici/undici:11576:11)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async t.streamResponse (/home/user/.vscode-oss/extensions/rjmacarthy.twinny-3.11.20-universal/out/index.js:2:135485)
```
**Desktop (please complete the following information):**
 - OS: Debian 13
- VSCodium 1.87.2

**Additional context**
using other provider still result the same
(i dont use litellm proxy server)

**Comment by FrozzDay** [comment]
turns out i really need to use litellm proxy to convert openai compatible api to openai compatible api

**Comment by rjmacarthy** [comment]
Hey, please could you provide more information for the request you are attempting?  Perhaps the API you are calling has CORS rules in place and using LiteLLM as a proxy is helping.

**Comment by FrozzDay** [comment]
no, it has no CORS. i can use it directly on other things (like sgpt cli)

**Comment by FrozzDay** [comment]
my bad guys, i realize i should put protocol in "Hostname" it should be domain only or ip only
