### ISSUE TITLE
Wrong language: getting python suggestions in Javascript file

### ISSUE THREAD

**Issue by Lastofthefirst** [rjmacarthy/twinny#225]
**Describe the bug**
The auto complete suggestions I get are in python in a javascript or rust file, even if I have valid javascript or rust already written in the file.

**Screenshots**

![Screenshot_20240425_181055](https://github.com/rjmacarthy/twinny/assets/47003973/7f8bb642-348c-46f7-8325-6660972b6c9d)

**Desktop**
 - OS: Debian
 - Vscodium

**Additional context**
I am using codellama 7b

**Comment by rjmacarthy** [comment]
Hello, please try to turn on the use file context option and try again.
