### ISSUE TITLE
Unable to select model when using Ollama

### ISSUE THREAD

**Issue by dchansen** [rjmacarthy/twinny#226]
**Describe the bug**
When modifying or adding a provider, the "model" field disappears when selecting "ollama". It is available for all other providers, such lmstuido or llamacpp.

**To Reproduce**
1. Click "Manage twinny providers"
1. Go to 'Add Provider'
2. Set 'Provider' to 'ollamawebui'.
4. Watch model field appear.
5. Set 'Provider' to 'ollama'.
6. Watch model field disappear.

**Expected behavior**
The model field should be available to allow the use of other models than codellama7b.

**Screenshots**
![ollamawebui](https://github.com/rjmacarthy/twinny/assets/5627428/b8d6cdc1-62f5-42ad-bd5e-160cabe39f5a)
![ollama](https://github.com/rjmacarthy/twinny/assets/5627428/00dfbe76-d228-479a-abc0-dd00739a66a5)

- OS: Windows

**Comment by dchansen** [comment]
Reinstalled the plugin, and now it correctly lists the models. Unsure what went wrong. 
Thanks for the quick reply and making a great plugin.

**Comment by rjmacarthy** [comment]
Thanks, I just applied a fix to fallback to the model name as a text box is the models are not fetched from the api correctly, many thanks.
