### ISSUE TITLE
command 'twinny.showSidebar' not found

### ISSUE THREAD

**Issue by nagman** [rjmacarthy/twinny#227]
**Describe the bug**
I tried to follow the instructions, and when I get to the "open sidebar" step, I get an error saying that this method doesn't exist.

**To Reproduce**
1. [Follow the steps 1 to 3 in the Getting Started section](https://github.com/rjmacarthy/twinny?tab=readme-ov-file#setup-with-ollama-recommended)
2. At step 4, instead of using the shortcut (that did nothing for me on a Mac), search for the command in the Cmd+Shift+P panel and trigger "Enable twinny sidebar"
3. You'll see an error : `command 'twinny.showSidebar' not found`

**Expected behavior**
I actually don't know what this sidebar should look like, but I guess this is why the autocompletion doesn't work for me (I do have the little robot emoji that spins when I type, but nothing happens).

**Screenshots**
![image](https://github.com/rjmacarthy/twinny/assets/16116486/7b9a30f9-5a26-4d5c-84c0-8db04e97c9a8)
![image](https://github.com/rjmacarthy/twinny/assets/16116486/3321c465-298a-49cc-ad89-5878ea904091)

**Desktop (please complete the following information):**
 - OS: MacOs Sonoma 14.4.1

**Additional context**
I must precise that I'm not sure that the step 2 has been completed, because it says "Set up Ollama as the backend by default: [Install Ollama](https://ollama.com/)". So I followed the link and installed Ollama, and it's running properly and I've been able to test the models using the Terminal prompt. But I haven't "Set up Ollama as the backend by default", because there are no instructions about how to do so. Is there something I must configure?
Also I've found that [this thread](https://github.com/rjmacarthy/twinny/issues/226) talks about selecting a model. So I tried to run the command "Manage twinny providers" using the Cmd+Shift+P panel, but nothing happens.

![image](https://github.com/rjmacarthy/twinny/assets/16116486/6ac47079-1fea-4609-b1be-d459eaa2718d)

**Comment by rjmacarthy** [comment]
Thanks for the report, I just fixed it.
