### ISSUE TITLE
Change shortcuts for suggestions

### ISSUE THREAD

**Issue by nagman** [rjmacarthy/twinny#228]
**Describe the bug**
I'd like to run the auto suggestion feature, but it doesn't seem to work.

The `Alt` + `\` shortcut isn't possible on my AZERTY keyboard. I'd like to change the keymaps, but I haven't found it in vs code.

Is the suggestion feature only triggered with this shortcut? Or is it supposed to run automatically upon typing, as with Github Copilot? If so, then that just doesn't work for me :(

**Desktop (please complete the following information):**
 - OS: Macos 14.4.1
 - Version: 3.11.30

**Comment by rjmacarthy** [comment]
Hello, you should be able to change the shortcuts in the vscode keybindings menu if your keyboard doesnt have certain keys, search for `twinny`.  Auto suggest should be enabled by default, the robot icon in the bar will spin if something is happening.  Please provide logs, api/provider details, model name and any further information related to your issue.

Thanks

**Comment by nagman** [comment]
I've set the keybinding to `editor.action.inlineSuggest.trigger`, but it does nothing (the robot icon doesn't spin).
There is no `twinny` keybinding related to `Trigger Inline Suggestion`:
![image](https://github.com/rjmacarthy/twinny/assets/16116486/fa7ff93d-f0c6-4131-87c7-b61fa64a8677)

I'm using:
- VS Code 1.88.1
- macOs 14.4.1
- Ollama 0.1.32
- model `codellama:7b-code` (digest `fc84f39375bcfe7612f7636a681ebb13d54eb4466e6ea6da07b5d1c37b49994d`)
- model `codellama:7b-instruct` (digest `8fdf8f752f6e80de33e82f381aba784c025982752cd1ae9377add66449d2225f`)

Are there others details you'd need?
