### ISSUE TITLE
Improve documentation for FIM

### ISSUE THREAD

**Issue by rburgst** [rjmacarthy/twinny#229]
**Is your feature request related to a problem? Please describe.**
I dont know how to properly set up twinny to get FIM to work. 

**Describe the solution you'd like**
I would like a clear explanation on what I have to configure using ollama (ideally codegemma, llama3 or deepseek)

**Describe alternatives you've considered**
checked issues, the docs

**Additional context**
currently trying with these settings but they dont work

<img width="478" alt="image" src="https://github.com/rjmacarthy/twinny/assets/22971/01834210-77df-4169-964d-c5a784134d79">

<img width="491" alt="image" src="https://github.com/rjmacarthy/twinny/assets/22971/c0d3ec00-cb1d-470e-b43d-0c5c177da63f">

**Comment by rjmacarthy** [comment]
Hello, please try `/api/generate` as the FIM path for ollama.  Here are some example configurations. 

https://github.com/rjmacarthy/twinny/blob/main/docs/providers.md

**Comment by rjmacarthy** [comment]
Executive decision: Individual configuration issues will receive an answer and will be considered closed after 24 hours of no replies. Many thanks.
