### ISSUE TITLE
Code completion works, but chat just spins the progress circle indefinitely

### ISSUE THREAD

**Issue by 2picus** [rjmacarthy/twinny#240]
### Discussed in https://github.com/rjmacarthy/twinny/discussions/238

<div type='discussions-op-text'>

<sup>Originally posted by **2picus** May  5, 2024</sup>
I have Twinny installed on Ubuntu Linux 22.04, and have installed the codellama:7b-instruct and codellama:7b-code providers via Ollama.  I have the Chat and Fill-in-middle providers set in the extension.  Inline suggestions work now, but when I enter a chat message, it just spins the progress circle and never completes.  What could be going on here?</div>

Confirmed to work in version 3.11.17, but not in latest version

**Comment by rjmacarthy** [comment]
Hey, thanks for the issue report.  Please could you confirm what settings you are using for chat provider?

**Comment by 2picus** [comment]
The latest version does seem to fix the problem.  Thanks!
