### ISSUE TITLE
FIM doesn't work with Keep Alive = -1

### ISSUE THREAD

**Issue by anaseinea** [rjmacarthy/twinny#246]
**Describe the bug**
FIM doesn't work with Keep Alive = -1

**To Reproduce**
set the Keep Alive setting to -1 then try autocomplete, you will get 400 error

**Logging**
![image](https://github.com/rjmacarthy/twinny/assets/15193634/88ae115e-af94-4be9-96ec-1a9b1a1971dd)

**API Provider**
Provide : Ollama

**Chat or Auto Complete?**
fim (auto-complete)?

**Desktop (please complete the following information):**
 Windows

**Comment by rjmacarthy** [comment]
Thanks for the report, I just fixed it in `v3.11.37`.
