### ISSUE TITLE
Cannot read long model names when configuring provider

### ISSUE THREAD

**Issue by fbl100** [rjmacarthy/twinny#249]
**Describe the bug**
I'm trying to use both codeqwen:7b-code-v1.5-fp16 and codeqwen:7b-chat-v1.5-fp16.  When I go to configure my providers, I see:
`codeqwen:7...-v1.5-fp16` listed twice in the dropdown list.  When I try to expand the panel, the text behind the ... does not get revealed.

**To Reproduce**
attempt to load both of these models and view them in the combo box

**Expected behavior**
At a bare minimum, I would want a tooltip that shows me the full model name when I hover over the dropdown.  Ideally the text area of the dropdown would scale so if you make the panel wider, you can see more text

**Screenshots**
![image](https://github.com/rjmacarthy/twinny/assets/22512174/4547b3f4-39f6-4b62-a70b-e2aa1348313b)

Note: I can't get a screenshot with the dropdown list expanded, but the same text is repeated twice.

This is the result of `ollama list`
![image](https://github.com/rjmacarthy/twinny/assets/22512174/ea2f5622-d44a-49b7-85b6-38150d4447f5)

**Logging**
N/A

**API Provider**
Ollama

**Chat or Auto Complete?**
Inability to know which is being used for Chat/Auto-Complete

**Model Name**
codeqwen:7b-code-v1.5-fp16
codeqwen:7b-chat-v1.5-fp16

**Desktop (please complete the following information):**
 - OS: Windows 11 / WSL2
 - Browser: N/A
 - Version 3.1

**Additional context**
N/A

**Comment by rjmacarthy** [comment]
Thanks for the report. I made a small improvement for it.
