### ISSUE TITLE
invalid option provided option=""

### ISSUE THREAD

**Issue by jgilfoil** [rjmacarthy/twinny#251]
**Describe the bug**
I'm seeing this error in my ollama server.log with every auto-complete request from twinny. Auto complete does appear to be working and giving valid completion suggestions, but i'm confused as to why it's generating this error as the options seem to be submitted properly.

```
time=2024-05-18T20:38:10.530-06:00 level=INFO source=server.go:545 msg="llama runner started in 3.42 seconds"
[GIN] 2024/05/18 - 20:38:11 | 200 |    4.5533999s |    <ip redacted> | POST     "/api/generate"
time=2024-05-18T20:38:33.016-06:00 level=WARN source=types.go:384 msg="invalid option provided" option=""
[GIN] 2024/05/18 - 20:38:33 | 200 |    611.9007ms |    <ip redacted> | POST     "/api/generate"
time=2024-05-18T20:38:41.256-06:00 level=WARN source=types.go:384 msg="invalid option provided" option=""
[GIN] 2024/05/18 - 20:38:41 | 200 |     274.131ms |    <ip redacted> | POST     "/api/generate"
time=2024-05-18T20:38:59.734-06:00 level=WARN source=types.go:384 msg="invalid option provided" option=""
[GIN] 2024/05/18 - 20:38:59 | 200 |    170.3256ms |    <ip redacted> | POST     "/api/generate"
time=2024-05-18T20:39:00.653-06:00 level=WARN source=types.go:384 msg="invalid option provided" option=""
[GIN] 2024/05/18 - 20:39:00 | 200 |    297.9836ms |    <ip redacted> | POST     "/api/generate"
time=2024-05-18T20:39:01.752-06:00 level=WARN source=types.go:384 msg="invalid option provided" option=""
[GIN] 2024/05/18 - 20:39:02 | 200 |    293.5611ms |    <ip redacted> | POST     "/api/generate"
time=2024-05-18T20:39:02.723-06:00 level=WARN source=types.go:384 msg="invalid option provided" option=""
[GIN] 2024/05/18 - 20:39:03 | 200 |    337.9314ms |    <ip redacted> | POST     "/api/generate"
```

**To Reproduce**
paste this short script. 
wait for autocomplete request

```
#!/bin/bash

# This script creates a backup of a directory and compresses it into a tar.gz file.

# Define the directory to backup
DIR_TO_BACKUP="/path/to/directory"

# Define the backup destination
BACKUP_DEST="/path/to/backup"
```

**Expected behavior**
Just trying to determine if Twinny is leveraging the options properly or if the errors mean `options: {}` is being discarded entirely.

**Logging**
```
[Extension Host] 
***Twinny Stream Debug***
Streaming response from <ip redacted>:11434.
Request body:
{
  "model": "codellama:7b-code-q4_0",
  "prompt": "<PRE># 

# Language: Shell (shellscript) 
# File uri: untitled:Untitled-2 (shellscript) 
#!/bin/bash

# This script creates a backup of a directory and compresses it into a tar.gz file.

# Define the directory to backup
DIR_TO_BACKUP=\"/path/to/directory\"

# Define the backup destination
BACKUP_DEST=\"/path/to/backup\"

 <SUF>  <MID>",
  "stream": true,
  "keep_alive": "5m",
  "options": {
    "temperature": 0.2,
    "num_predict": 512
  }
}


Request options:
{
  "hostname": "<ip redacted>",
  "port": 11434,
  "path": "/api/generate",
  "protocol": "http",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json",
    "Authorization": ""
  }
}


    
console.ts:137 [Extension Host] Streaming response end due to multiline not required  61 
Completion: # Define the name of the backup

console.ts:137 [Extension Host] *** Twinny completion triggered for file: untitled:Untitled-2 ***
      Original completion: # Define the name of the backup

      Formatted completion: # Define the name of the backup
      Max Lines: 30
      Use file context: true
      Completed lines count 1
      Using custom FIM template fim.bhs?: false
```

**API Provider**
ollama -v
Warning: could not connect to a running Ollama instance
Warning: client version is 0.1.38

**Chat or Auto Complete?**
auto complete

**Model Name**
codellama:7b-code-q4_0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: I don't think a browser is involved in this example

**Additional context**
Both Ollama and vscode are running from windows 10, though i have tried this with vscode using a remote linux container and got the same result.

I tried resetting all twinny settings back to default (except for the host ip), as i'm using this in remote containers sometimes, so it needs to be network accessible.

**Comment by Tabrizian** [comment]
Running into a similar issue:

```
[GIN] 2024/06/01 - 14:47:55 | 200 |  639.312645ms |      172.17.0.1 | POST     "/v1/chat/completions"
time=2024-06-01T14:47:59.879Z level=WARN source=types.go:384 msg="invalid option provided" option=""
```

**Comment by parrt** [comment]
I get same error via manual POST via python requests lib for /api/generate.  I pass `options` as a dictionary. weird.

**Comment by valentinfrlch** [comment]
Has anyone figured this out? Happens to me too. This is the dictionary that's sent:
```python
data = {
     "model": model,
      "messages": [{
            "role": "user",
            "content": message
        }],
      "stream": False,
       "options": {
           "max_tokens": max_tokens,
            "temperature": temperature
            }
        }
```

Both `max_tokens` and `temperature` are never None

This is the log entry:
```
time=2024-06-25T20:13:55.877Z level=WARN source=types.go:430 msg="invalid option provided" option=""
[GIN] 2024/06/25 - 20:13:56 | 400 |  130.044154ms |    172.16.16.35 | POST     "/api/chat"
```

**Comment by lbux** [comment]
> Has anyone figured this out? Happens to me too. This is the dictionary that's sent:
> 
> ```python
> data = {
>      "model": model,
>       "messages": [{
>             "role": "user",
>             "content": message
>         }],
>       "stream": False,
>        "options": {
>            "max_tokens": max_tokens,
>             "temperature": temperature
>             }
>         }
> ```
> 
> Both `max_tokens` and `temperature` are never None
> 
> This is the log entry:
> 
> ```
> time=2024-06-25T20:13:55.877Z level=WARN source=types.go:430 msg="invalid option provided" option=""
> [GIN] 2024/06/25 - 20:13:56 | 400 |  130.044154ms |    172.16.16.35 | POST     "/api/chat"
> ```

I'm starting to think this is an Ollama issue as I found this github issue when searching for the same message despite not using twinny. In my case, I don't think my tool calls in options are being properly passed to Ollama

**Comment by chriss1245** [comment]
It happends to me as well. I am using OllamaFunctions from langchain-experimental package. When i make an invocation I see that. At first I thought it was related to a problem with the way the parameters are sent to the endpoint. But now I am starting to think  it is ollama related.

**Comment by LaansDole** [comment]
> Running into a similar issue:
> 
> ```
> [GIN] 2024/06/01 - 14:47:55 | 200 |  639.312645ms |      172.17.0.1 | POST     "/v1/chat/completions"
> time=2024-06-01T14:47:59.879Z level=WARN source=types.go:384 msg="invalid option provided" option=""
> ```

I have the same error, apparently Ollama just decided not to resolve this warning and close the issue

**Comment by mdmazharali786** [comment]
Getting same message and unable to understand the issue.

time=2024-12-17T16:00:24.520Z level=INFO source=server.go:594 msg="llama runner started in 11.80 seconds"
[GIN] 2024/12/17 - 16:00:24 | 200 | 12.109073817s |       127.0.0.1 | POST     "/api/chat"
time=2024-12-17T16:01:21.423Z level=WARN source=types.go:509 msg="invalid option provided" option=tfs_z
[GIN] 2024/12/17 - 16:01:21 | 200 |   25.909282ms |       127.0.0.1 | POST     "/api/chat"

**Comment by eugene-can** [comment]
Getting the same message:

```
time=2025-02-13T09:22:07.596-05:00 level=WARN source=types.go:512 msg="invalid option provided" option=tfs_z
[GIN] 2025/02/13 - 09:22:07 | 200 |     43.1227ms |       127.0.0.1 | POST     "/api/embed"

```

**Comment by jamesjsanders** [comment]
Getting the same when using OpenWebUI with ollama (gemma3:27b)

time=2025-04-13T16:22:41.465Z level=WARN source=types.go:524 msg="invalid option provided" option=penalize_newline
