### ISSUE TITLE
Codeqwen uses same FIM template as stable-code

### ISSUE THREAD

**Issue by BeRT2me** [rjmacarthy/twinny#252]
`codeqwen:code` seems to use the same FIM template as `stable-code`

Adding `codeqwen` to the dropdown list (And pointing it to `stable-code`'s template) would be appreciated!

**Comment by rjmacarthy** [comment]
Hey it looks the same template, I will add it anyway, maybe future models will be better.

**Comment by rjmacarthy** [comment]
Added
