### ISSUE TITLE
Add OpenAI provider

### ISSUE THREAD

**Issue by JamesClarke7283** [rjmacarthy/twinny#255]
**Is your feature request related to a problem? Please describe.**
Its annoying that all the locally hosted models are not so good with code as GPT4o, its to be expected, but i would like to see a OpenAI provider added.

**Describe the solution you'd like**
In the dropdown list of providers, i would like to see a OpenAI provider, and a drop down to select a OpenAI model.

**Describe alternatives you've considered**
Alternatively, allow us to make our own providers easily without code, but that might be a bit difficult to do.

**Additional context**
N/A

**Comment by rjmacarthy** [comment]
Hello, you can use OpenAI by using the LiteLLM provider proxy.

**Comment by walkandre** [comment]
Just add a new provider with the settings:
<img width="553" alt="image" src="https://github.com/rjmacarthy/twinny/assets/9648/86ddedec-8273-4a28-b8ad-c026a2cda1aa">

**Comment by JamesClarke7283** [comment]
Oh, thanks, i will keep that in mind.
I did not see OpenAI anywhere in the docs, so thats why i could not find out. But thanks/

**Comment by bareblackfoot** [comment]
@walkandre where is this setting in the vscode?

**Comment by rjmacarthy** [comment]
> @walkandre where is this setting in the vscode?

You should click the plug icon at the top. You should also install a local proxy for OpenAI such as LiteLLM or similar.

**Comment by bareblackfoot** [comment]
@rjmacarthy 
Thanks! it worked. The chat model works fine. However, the gpt3.5-turbo-instruct model for FIM generates <PRE> and <MID> tokens. Do you know how can i fix it?

**Comment by rjmacarthy** [comment]
> @rjmacarthy Thanks for your fast response! I found the button and it worked well. The chat model works fine. However, the gpt3.5-turbo-instruct model for FIM generates <PRE> and <MID> tokens. Do you know how can i fix it?
> 
> ```
> Providers
> Label*: OpenAI FIM
> Type*: fim
> Fim Template*: automatic
> Provider*: litellm
> Protocol*: http
> Model name*: gpt-3.5-turbo-instruct
> Hostname*: 0.0.0.0
> Port*: 34162
> API path*: /chat/completions
> ```

Hey I'm not sure about FIM with OpenAI API...I saw some legacy stuff before but never tested it. You could try a custom FIM template or explore the API docs. Please let me know how you get on.
