### ISSUE TITLE
Anything after <file_sep> to be stripped from completion

### ISSUE THREAD

**Issue by robertpiosik** [rjmacarthy/twinny#268]
**Describe the bug**
When using starcoder2:3b my completions contain fim tokens.
My workaround is to split output on <file_sep>.

**To Reproduce**
starcoder2:3b with ollama

**Screenshots**
![image](https://github.com/twinnydotdev/twinny/assets/7120725/032ea71c-5185-4c4b-b8ea-ce801ed3a2ac)
![image](https://github.com/twinnydotdev/twinny/assets/7120725/394d9ded-ce14-42fc-8b4d-16784a73aeff)

**Comment by rjmacarthy** [comment]
Hello, I just released a new version which adds `<fim_sep` to stop words for starcoder models. Many thanks.

https://github.com/twinnydotdev/twinny/commit/057c1a17a4474c22172d1f916dc657f0e0c6de66

**Comment by rjmacarthy** [comment]
Hello @robertpiosik the change to remove the stop word is th correct approach, in order for you to continue working with starcoder2 you need to create th correct Modelfile for Ollama and specify your stop words in the configuration. All the best. https://github.com/ollama/ollama/blob/main/docs/modelfile.md#valid-parameters-and-values

**Comment by rjmacarthy** [comment]
Hey @robertpiosik did that work for you? Many thanks.

**Comment by rjmacarthy** [comment]
Ok no worries. Thanks for the help, all the best!
