### ISSUE TITLE
Add support for Bearer tokens

### ISSUE THREAD

**Issue by oxaronick** [rjmacarthy/twinny#33]
### Problem

I've deployed Ollama and [Ollama WebUI](/ollama-webui/ollama-webui) on a VM to provide chat-style AI to a development team. It's working very well and Ollama WebUI is under active development, adding features weekly.

I'd like to also provide code completion to the dev team. Since I'm running Ollama on a server, this means making requests from every developer's machine to the server. This means I need to have authentication in place.

### Possible solution

Ollama WebUI has a feature where it will proxy requests to the Ollama server as long as you have a valid Bearer token in an HTTP header.

What do you think of adding an extension setting that would:

1. let the user set an HTTP Bearer token
2. include it in the "Authorization" header on requests to the backend

?

If Twinny could do this, it would mean admins don't have to put some other form of authentication in place in front of Ollama in order to offer code completion via their Ollama server.

**Comment by rjmacarthy** [comment]
Hey thanks for the input. Yes, I agree  it's a good idea.

I am happy to apply this change and  I will update soon with a new PR.

**Comment by rjmacarthy** [comment]
Fixed in 2.6.2, thanks for the support.

**Comment by rcgtnick** [comment]
Working well for me. Thanks!

**Comment by rcgtnick** [comment]
It turns out Twinny is not actually sending the Authorization header. (When testing this originally I had mistakenly sent the requests to a port that didn't require authentication.)

I can make a successful request with `curl`, and here are the headers it's sending (from `tcpdump` on the server, behind a TLS-terminating reverse proxy):

```
POST /ollama/api/generate HTTP/1.1
X-Real-IP: X.X.X.X
X-Forwarded-For: X.X.X.X
X-Forwarded-Proto: https
X-Forwarded-Host: some.hostname.io
Host: some.hostname.io
Connection: close
Content-Length: 58
User-Agent: curl/8.4.0
Accept: */*
Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxx-xxxxx
Content-Type: application/x-www-form-urlencoded
```

With Twinny v2.6.8, I see these headers:

```
POST /ollama/api/generate HTTP/1.1
X-Real-IP: X.X.X.X
X-Forwarded-For: X.X.X.X
X-Forwarded-Proto: https
X-Forwarded-Host: some.hostname.io
Host: some.hostname.io
Connection: close
Content-Length: 1574
```

**Comment by rcgtnick** [comment]
No change on 2.6.9.

**Comment by rcgtnick** [comment]
There is a `streamResponse` call in utils.ts in which the Bearer token seems to be added to headers. However, there's also a `streamResponse` call in completions.ts, in which the header does not seem to be added.

(I've tried adding headers to the latter and running the extension from source, but I get an error "property 'score' does not exist on string", and I don't know enough about TS to fix that!)

**Comment by rcgtnick** [comment]
Looks like that was it - I managed to stuff this header in by editing the extension directly, and in `provideInlineCompletionItems` I added this:

```js
const headers = {
    "Authorization": "Bearer " + this._config.get("ollamaApiBearerToken")
};
...
{
  hostname: this._baseurl,
  port: this._apiport,
  method: "POST",
  path: "/ollama/api/generate",
  headers
},
```

**Comment by lkonga** [comment]
> Looks like that was it - I managed to stuff this header in by editing the extension directly under `~/.vscode`, and in `provideInlineCompletionItems` I added this:
> 
> ```js
> const headers = {
>     "Authorization": "Bearer " + this._config.get("ollamaApiBearerToken")
> };
> ...
> {
>   hostname: this._baseurl,
>   port: this._apiport,
>   method: "POST",
>   path: "/ollama/api/generate",
>   headers
> },
> ```

Hi @rcgtnick, is this workaround still needed for using ollama via ollama webui or has it been fixed?

I am trying to use the extension with ollama webui but is not able to communicate with it.

**Comment by rcgtnick** [comment]
Hey @lkonga, the workaround is no longer required. Twinny now has a setting called `twinny.apiBearerToken` that handles this.
