### ISSUE TITLE
Allow setting base path on the server

### ISSUE THREAD

**Issue by rcgtnick** [rjmacarthy/twinny#37]
I'm trying to use Twinny to access Ollama via [Ollama WebUI](/ollama-webui/ollama-webui). Ollama WebUI forwards any requests to `/ollama` to Ollama. So for this to work, a client needs to send requests to `/ollama/api/generate`.

However, There is no way to set the path in Twinny settings.

Also, adding another setting that is used to build the URL might be too many settings. The "Use TLS", "hostname", "port", and "path" settings could all be specified by taking a base URL from the user:

`https://some.server.io:8443/ollama`

Then the extension could append `/api/generate`.

This can also be done in a reverse proxy by rewriting the URL but it would be nice not to have to.

**Comment by rjmacarthy** [comment]
Thank you, it's a good suggestion and I understand the requirement.

If you want to make a PR to update this feel free, or I'll update it for a future release.

Many thanks.

**Comment by rcgtnick** [comment]
I'd be happy to play around with this, but I'm stuck on an error right now trying to run your extension from source.

If you have any tips for this error, lmk, otherwise I'll keep poking at it when I have time.

<img width="1047" alt="image" src="https://github.com/rjmacarthy/twinny/assets/86964206/1c30d181-3106-4d40-bcb3-95cb43715b8d">

Same error prevents the extension from launching.

**Comment by rcgtnick** [comment]
Fixed in v3.0.0.
