### ISSUE TITLE
vLLM Integration

### ISSUE THREAD

**Issue by randomVariable2** [rjmacarthy/twinny#40]
Integration of twinny with the popular [vLLM](https://github.com/vllm-project/vllm) backend can allow a wide range of new use cases, especially on multiuser environments.

**Comment by rjmacarthy** [comment]
Hey, this should in theory work now by using the LMStudio option and configuring the api endpoints correctly.  Please try and report back.

Many thanks,

**Comment by piulin** [comment]
I can confirm that vllm servers work with the LMStudio option.
