### ISSUE TITLE
Add support for FIM Codestral API

### ISSUE THREAD

**Issue by robertpiosik** [rjmacarthy/twinny#405]
Hi, codestral api requires "suffix" to be sent in a separate key; https://docs.mistral.ai/api/#tag/fim/operation/fim_completion_v1_fim_completions_post

Could twinny support that? Thank you.

**Comment by rjmacarthy** [comment]
Annoyingly this is different from the OpenAI standard and I am not in a hurry to support multiple different API providers, maybe we could come up with a way to make it configurable without hard-coding everything based on provider choices.
