### ISSUE TITLE
llama.cpp api

### ISSUE THREAD

**Issue by kv-gits** [rjmacarthy/twinny#45]
**Is your feature request related to a problem? Please describe.**
Llama.cpp provides nice options to run local models in gguf format using both gpu and cpu at the same time

**Describe the solution you'd like**
Want to use llama.cpp as backend for twinny

**Describe alternatives you've considered**
Ollama need docker which is rather uncomfortable.

**Comment by rjmacarthy** [comment]
Thanks @kv-gits for the suggestion it's possible. Do you know which model would support FIM completions using llama.cpp?

**Comment by kv-gits** [comment]
As I found in issues, llama.cpp supports FIM tokens and all three models of tweeny have their gguf version on TheBloke HF

**Comment by rjmacarthy** [comment]
Thanks for that I am creating a new release now version 3 which adds support for llama.cpp.  You'll need to update some settings in the extension for it to work. FIM is working with the model I tried, but with the same model chat is spitting out garbage, there is an option to use a different endpoint for chat if required.

**Comment by rjmacarthy** [comment]
I think there was a small bug which still checked for model availability on Ollamo on `v3.0.0`  I fixed it and released `3.0.2` to stop this check.

**Comment by kv-gits** [comment]
Would be nice to turn off "install ollama" window after install, and also provide some example cmd to run llamacpp server for quick start
