### ISSUE TITLE
Wishlist - Gguf compatibility

### ISSUE THREAD

**Issue by wweevv-johndpope** [rjmacarthy/twinny#5]
I'm using this - https://huggingface.co/TheBloke/Phind-CodeLlama-34B-Python-v1-GGUF

Works with llama.cpp 
I couldn't get it working with oogabooga but need ui.

**Comment by rjmacarthy** [comment]
Thank you for your suggestion to add GGUF models, it's a good idea.

**Comment by rjmacarthy** [comment]
Hey, now that twinny uses ollama API you can use gguf models with it. Thanks.
