### ISSUE TITLE
Call the plugin on request only

### ISSUE THREAD

**Issue by LeonardoGentile** [rjmacarthy/twinny#52]
Hello, 
right now it seems that once activated the plugin runs all the time, trying to complete the code as we press keys in vscode. 

This is what I'd want most of the times but **not always**, sometimes the plugins just gets in the way by proposing its completion and I have to press esc all the times to cancel them.

Ideally I'd like to call the plugin when I need it by pressing a shortcut or call a command. 
I mean, I'd like to keep it disabled until I decide when it should be enabled on my request.

Is this possible right now? If it isn't it would be nice to have this feature, to both have more control and don't show annoying completions but also to limit the cpu limit when it's not necessary the plugin use.

**Comment by rjmacarthy** [comment]
Hey thanks for the suggestion, no pun intended!

I just released version `v3.0.8` which includes a new option to disable auto suggestions, you could either use this or update the debounce time to stop so many completions.  The default to trigger completions is `Alt+\`.

Hope this helps, any problems let me know.

Many thanks

**Comment by max-wittig** [comment]
@rjmacarthy I have the opposite problem. Seems like the autocomplete does not work. I haven't been able to figure out a way to enable it.

**Comment by rjmacarthy** [comment]
Hey @max-wittig please could you open a new issue with some re-production steps?  E.g what model you are using, what hardware, if there are any errors or any other useful information which might help fix it? 

Many thanks

**Comment by rjmacarthy** [comment]
Fixed.
