### ISSUE TITLE
Keys to focus on the chat prompt and send messages

### ISSUE THREAD

**Issue by LeonardoGentile** [rjmacarthy/twinny#57]
Probably these keys (and commands) already exist and I couldn't find them.
If not I guess they should be introduced:
- focus on the chat (the command `show twinny` just open the sidebar but doesn't focus on the chat input)
- key to send message (I though it should the "standard" cmd-Enter but it's not)
- key to stop message generation

**Comment by rjmacarthy** [comment]
Hey, I just added new keybindings.
