### ISSUE TITLE
Bug: Settings modified do not apply immediately

### ISSUE THREAD

**Issue by allen-li1231** [rjmacarthy/twinny#6]
# Expected Behavior
Any change in configurations in settings (either in JSON file or UI) is supposed to be applied immediately.

# Actual Behavior
User will have to reload window or reactivate extension to make an apply.

# My Suspection
Probably because the configurations are stored in CompletionProvider when extension is activated, and never to be update afterwards. 
To fix it:
* Make use of workspace.onDidChangeConfiguration method.
* Always get a new twinny configuration instance from workspace when it is to be used.

**Comment by rjmacarthy** [comment]
Thanks for your contribuion @allen-li1231 !
