### ISSUE TITLE
Custom buttons with prompts

### ISSUE THREAD

**Issue by AntonKrug** [rjmacarthy/twinny#60]
**Is your feature request related to a problem? Please describe.**
I started using the plugin for non-coding sections as well, rephrasing comments, cleaning grammar in readme...
And have to type manually the prompts like "Rephrase the following text" while having selected comment/parahraph of text selected

**Describe the solution you'd like**
Ability to add custom buttons alongside the `Refactor`, `Explain` ... buttons with my own custom prompt

**Describe alternatives you've considered**
Typing the prompt manually so far works, but having custom buttons for whatever use-cases i will find the plugin useful would be amazing.

**Comment by rjmacarthy** [comment]
Hey @AntonKrug thank you for the suggestion.  

I think that this should be possible, we just need to decide on where the best place to store the templates would be and in which format in order to parse them back into prompts for the LLM with context.

I was considering something like handlebars or similar template producing languages, if you know of a good solution for this already please let me know.  

Many thanks

**Comment by rjmacarthy** [comment]
Hey, thanks for the suggestion, it's also been mentioned before by others.

I just released version `3.2.0` which includes the ability to edit the prompt templates, there is a setting at the top of the sidebar which will open up an editor with the default prompt templates inside.  

I am working towards being able to specify your own templates in future releases.

Many thanks,

**Comment by technovangelist** [comment]
yes, now that the templates are accessible, being able to add new ones and have it create the buttons would be great.

**Comment by rjmacarthy** [comment]
Please check 3.4.0 fully customisable templates added.

**Comment by rjmacarthy** [comment]
A fresh install should have done it. I'm not sure about Windows however, maybe not working as expected as you say? It should copy the default templates to that directory when you install the extension.

**Comment by AntonKrug** [comment]
Permissions should be fine, the files physically are there, but the path for some reason is containing URL escaped backslashes instead of the genuine slashes. So `C:\Users`  folder exists, but `C:%5VUsers` is not:
![image](https://github.com/rjmacarthy/twinny/assets/30338596/45f11410-2167-4b98-9d32-adc1f6554a6c)

**Comment by AntonKrug** [comment]
As well on windows you want the drive letter as well, if you do just something like linux it might see it differently and append it to the path as escaped URL, looks like it tries to access `\Users` which doesn't exist

**Comment by AntonKrug** [comment]
Tried making a PR, wondering if this could help?

**Comment by rjmacarthy** [comment]
Thanks @AntonKrug I just merged and released a new version with your changes, please let me know how you get on.

Many thanks,

**Comment by AntonKrug** [comment]
You welcome, it's lovely pluging, hope i will get to contribute to it more often.
Tested it on one machine and it works, i will test it on slightly different windows 10 machine later and then i can close the issue.

![image](https://github.com/rjmacarthy/twinny/assets/30338596/65607954-fae4-489e-9383-cec51291867c)

**Comment by AntonKrug** [comment]
The templates open on the other machine as well
