### ISSUE TITLE
Add the option to configure the Chat with custom instructions.

### ISSUE THREAD

**Issue by CompositeCoding** [rjmacarthy/twinny#62]
### Feature Ask
Currently, I find the LLM in the chat quite lengthy, I would like to add custom pre-configured messages to change its writing style e.g., 'be concise'.  This can either be an extra button with a pop-up or a field on the settings page. 

I pulled the repo locally, so I can make the change myself once approved :)

**Comment by rjmacarthy** [comment]
Hey, thanks for the suggestion, it's also been mentioned before by others.

I just released version `3.2.0` which includes the ability to edit the prompt templates, there is a setting at the top of the sidebar which will open up an editor with the default prompt templates inside.  

I am working towards being able to specify your own templates in future releases.

Many thanks,
