### ISSUE TITLE
Really want to be able to specify the fim and chat templates. 

### ISSUE THREAD

**Issue by technovangelist** [rjmacarthy/twinny#63]
Today I am stuck with using only CodeLlama even though I find DeepSeek Coder to be much better. And Infilling with the 1.6b parameter model is amazing. Could you add the ability to add custom templates, or do like Llama Coder extension which defines templates for codellama, deepseek coder, and one other. 

Other than that one issue, Twinny is my favorite for vscode AI Assistants. I posted this yesterday about Llama Coder and plan to do an update for Twinny. https://www.youtube.com/watch?v=fT-sUUq48Xk

**Comment by rjmacarthy** [comment]
Hey, thanks for the suggestion.

I just released version `3.2.0` which includes the ability to edit the prompt templates, there is a setting at the top of the sidebar which will open up an editor with the default prompt templates inside.  

I am working towards being able to specify your own templates in future releases.

In terms of supporting different fim templates, I will add different built in fim templates for deepseek and stable code too along with the existing llama template.

Any questions please reach out,

Many thanks,

**Comment by rjmacarthy** [comment]
Hey, support for FIM stablecode and deepseek has now been added. Please let me know how you get on with it.

Many thanks,

**Comment by rjmacarthy** [comment]
Please check 3.4.0 fully customisable templates added.

**Comment by vivasvan1** [comment]
Its generating garbage on 

```json
{

  "twinny.chatModelName": "deepseek-coder:1.3b-base-q4_1",
  "twinny.fimModelName": "deepseek-coder:1.3b-base-q4_1",
  "twinny.useFileContext": true,
  "twinny.temperature": 0.8,
  "twinny.fimTemplateFormat": "deepseek"
  "twinny.enableLogging": true
}
```

![image](https://github.com/rjmacarthy/twinny/assets/21074796/d2dfb8cd-af54-4ed8-86f9-5c9bfc087824)


If there is something wrong in my config feel free to correct me.

**Comment by rjmacarthy** [comment]
Maybe a different model or prompt template would help?
