### ISSUE TITLE
Settings: api url is confusing

### ISSUE THREAD

**Issue by technovangelist** [rjmacarthy/twinny#66]
**Describe the bug**
In settings for the extension, there is a box for the API Url. I assume this used to be the full url then you added the paths and ports. It looks like it is actually just the host name. 

**Screenshots**
![CleanShot 2024-02-02 at 06 05 14](https://github.com/rjmacarthy/twinny/assets/633681/f368a607-f2eb-4d4c-a194-e2ffa5d0ce02)

**Desktop (please complete the following information):**
 - MacOS

**Comment by rjmacarthy** [comment]
I renamed it to host name now.
