### ISSUE TITLE
Completions not working with ollama via ollama webui

### ISSUE THREAD

**Issue by lkonga** [rjmacarthy/twinny#67]
### Problem
Unable to use twinny (no completions) when setting up ollama via ollama webui despite specifying bearer token.
I wonder if as mentioned [here](https://github.com/rjmacarthy/twinny/issues/33#issuecomment-1898637431) bearer token is not really fully supported and there's still need of a workaround?

Adding screenshot of config for reference:
![Screenshot from 2024-02-02 18-40-00](https://github.com/rjmacarthy/twinny/assets/2558702/f432705d-6e88-42ca-9f2e-c9607465a689)

**Comment by technovangelist** [comment]
why would you use the webui? Just use Ollama directly.

**Comment by rjmacarthy** [comment]
I'm not sure what could be causing it, but can look into it. Thanks for the report.

**Comment by dlford** [comment]
> why would you use the webui? Just use Ollama directly.

I can't speak for the person who opened this issue, but I use the webui to secure ollama because it's exposed to the internet.

**Comment by kha84** [comment]
> I'm hitting the same issue, confirmed the bearer token is working with Postman. I've enabled "debug" in Twinny settings but can't seem to find the output anywhere, my Ollama server does not see any requests being made by Twinny.

I struggled with the same question. Here is how to view debug - https://github.com/rjmacarthy/twinny/issues/72#issuecomment-1937013659

Give it another try with your ollama web ui, but update the Twinny first to the latest version. 
@rjmacarthy recently made some changes so Twinny now supports oobabooga, it might be the case that integration with ollama web ui was also fixed.

**Comment by dlford** [comment]
@kha84 oh I see, the logs are in the webview devtools console.

I did some more testing today and I think the bearer token is working, as the wrong token gets a `401` response as it should. But using the correct token this is what I get:

![ksnip_20240211-135547](https://github.com/rjmacarthy/twinny/assets/22881850/1d321c92-d0f6-4023-92f5-ab16cf46f364)

**Comment by kha84** [comment]
I'm not the author and no JS programmer myself, but based on a error it looks like the ollama-web-ui OpenAI API endpoint timeouts. Are you able to get responses if you send same request with using curl? The the #72 for examples how I did that for oobabooga/textgen-webui
Paste your output from running curl here, it might help @rjmacarthy to pin that down.

It looks like every inference software who claims to be OpenAI-API-compatible is still doing some things differently from each other.

**Comment by dlford** [comment]
Interestingly, I only see the request in the ollama and webui pods when the token is invalid (401 unauthorized), when using the correct token there is no output from either in the logs.

**Comment by dlford** [comment]
Even more interestingly, using the Twinny chat sidebar completely hangs the Ollama server, it will not respond to any `generate` or `chat` requests after that has been attepmted until I restart the container it's running in.

Here is the output of the `curl` request, seems to work fine and not cause any hangs:

![ksnip_20240211-160450](https://github.com/rjmacarthy/twinny/assets/22881850/3f0263d7-186b-4072-8c6b-e322bae02709)

**Comment by dlford** [comment]
Twinny Settings:

```json
{
  "twinny.apiHostname": "ollama.redacted-hostname.tld",
  "twinny.chatApiPort": 443,
  "twinny.fimApiPort": 443,
  "twinny.useTls": true,
  "twinny.apiBearerToken": "REDACTED",
  "twinny.chatApiPath": "/ollama/api/generate",
  "twinny.fimApiPath": "/ollama/api/generate",
  "twinny.enableLogging": true
}
```

**Comment by kha84** [comment]
Yeah, you see, in my example (for Jan.ai) the JSON for streamed responses looked different https://github.com/rjmacarthy/twinny/issues/72#issuecomment-1937180856

I'm pretty sure that different software wrap streamed responces into JSON differently. To support them all plugin needs to expose some configuration setting, a sort of path inside of JSON, where you can hint it, where exactly to look at for responces in the responded JSON. I hope @rjmacarthy will figure it out how it can be done, so all the users of different inference apps will get their silver bullet

**Comment by dlford** [comment]
Haha of course, it would be too easy if everyone just agreed on a standard and stuck with it :joy:.

Thanks @kha84 for your insights!

@rjmacarthy please let me know if you need anything else from me on this issue.

**Comment by rjmacarthy** [comment]
Hey I did some debugging, but I am really not sure why it's not working right now, sorry.

**Comment by dlford** [comment]
@rjmacarthy any way I can help? I can add a user for you on my Ollama server for debugging?

**Comment by rjmacarthy** [comment]
Hey @dlford I think it's due to ollama webui backend supporting `text/event-stream` with `stream: false` for the `content-type` request header and all of the other API's which are supported use `application/json` and `stream: true`.  I ran everything locally even the ollama webui server and requests we're working after I hacked authentication and cors but we're ending pre-maturely due to content-length errors, so I need more time or help.

**Comment by dlford** [comment]
@rjmacarthy that's weird, I'll try to find some time to explore the code base and tinker a bit.

**Comment by rjmacarthy** [comment]
Update: I think it's fixed now...I just tested it and it seems to work as long as the auth credentials are correctly set.  Please test on the latest version and let me know, thanks.

**Comment by rjmacarthy** [comment]
I'll update the readme soon with Ollama web UI support. Many thanks for the help and the donation too!
