### ISSUE TITLE
command enter doesn't work to get out of text box

### ISSUE THREAD

**Issue by technovangelist** [rjmacarthy/twinny#68]
**Describe the bug / feature**
when in the text box in the chat sidepane, I have to click the button to have the model respond. Everywhere else, command enter, or the corresponding shortcut on windows, will automatically leave the box and accept it. 

its kind of a bug.... but maybe it’s a new feature. not sure

**Comment by rjmacarthy** [comment]
Hey, does CTRL+Enter work?

**Comment by ericvrp** [comment]
ctrl+entrer works on Mac but command+enter is maybe the expected key combination?

**Comment by rjmacarthy** [comment]
Stale
