### ISSUE TITLE
twinny in Windows

### ISSUE THREAD

**Issue by engdante** [rjmacarthy/twinny#70]
Ollama is not officially supported for Windows. But it works fine in WLS.
Even though olama is launched under WLS, Twinny does not recognize this and wants to install it on a Windows host.

Is it possible to check if localhost:11434 is active and work with that?
or
to contact the WLS directly if this is possible.

![image](https://github.com/rjmacarthy/twinny/assets/24808583/31f0a814-26c4-4a6e-9e72-9c367b7b2a31)

**Comment by rjmacarthy** [comment]
Hey, thanks for the report.

Yes, this area could do with some improvements. 

There is an option to disable server checks if you want to skip this each time and it's persistent across sessions.

Many thanks,

**Comment by sonicviz** [comment]
Hi, 

Thanks for the project, I'm going to see if I can get it running with Docker as per https://dev.to/liukonen/unleashing-the-power-of-developer-ai-a-journey-into-hosting-a-private-llmcode-assistant-locally-4kma
Bit short on space on my C drive atm so I don't have WSL installed.

Will see!

**Comment by kiorull** [comment]
Just wanted to report that it works perfectly with:
- Windows 11
- Nvidia RTX 4070Ti
- Docker Desktop v4.27.1 
- Ollama latest + Nvidia container toolkit latest:
   - docker run -d --gpus=all -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
   - docker exec -it ollama ollama pull codellama:7b-instruct
   - docker exec -it ollama ollama pull codellama:7b-code
- VSCode 1.86.0 (make sure it's updated, latest versions of Twinny do not work on older VSCode)
- Twinny 3.4.0 with OOB settings + Disable Server Checks

Tested with both Windows workspace and WSL2 workspace (Ubuntu 22.04 LTS).

Many thanks @rjmacarthy, it's really snappy and responsive.

**Comment by sonicviz** [comment]
By windows workspace do you mean Hyper-V? I thought the NVidia Container Toolkit only works with WSL2?

**Comment by ChainsawGarden** [comment]
> Just wanted to report that it works perfectly with:
> 
> * Windows 11
> * Nvidia RTX 4070Ti
> * Docker Desktop v4.27.1
> * Ollama latest + Nvidia container toolkit latest:
>   
>   * docker run -d --gpus=all -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
>   * docker exec -it ollama ollama pull codellama:7b-instruct
>   * docker exec -it ollama ollama pull codellama:7b-code
> * VSCode 1.86.0 (make sure it's updated, latest versions of Twinny do not work on older VSCode)
> * Twinny 3.4.0 with OOB settings + Disable Server Checks
> 
> Tested with both Windows workspace and WSL2 workspace (Ubuntu 22.04 LTS).
> 
> Many thanks @rjmacarthy, it's really snappy and responsive.

Where is the option to disable server checks? There's an option to disable twinny.

**Comment by kiorull** [comment]
@sonicviz workspace as in WS workspace. And yes, Nvidia container toolkit I installed in WSL2 and issued the docker command from WSL2. Sorry, forgot to mention that in the original post.
@ChainsawGarden In Twinny extension settings:
![image](https://github.com/rjmacarthy/twinny/assets/108837832/d46f796d-8ee0-4802-b693-350c2538919f)
@autoferrit try to start the docker from WSL2, this is what I did to be more exact. In docker desktop it shows like this:
![image](https://github.com/rjmacarthy/twinny/assets/108837832/8e022995-919e-4f4b-b504-085c13c4938b)
Also if I click the small icon next to the port, it opens in chrome fine:
![image](https://github.com/rjmacarthy/twinny/assets/108837832/c6a5c8cd-a0d7-45da-aea9-8e531a827426)

**Comment by jinglesthula** [comment]
> > Just wanted to report that it works perfectly with:
> > 
> > * Windows 11
> > * Nvidia RTX 4070Ti
> > * Docker Desktop v4.27.1
> > * Ollama latest + Nvidia container toolkit latest:
> >   
> >   * docker run -d --gpus=all -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
> >   * docker exec -it ollama ollama pull codellama:7b-instruct
> >   * docker exec -it ollama ollama pull codellama:7b-code
> > * VSCode 1.86.0 (make sure it's updated, latest versions of Twinny do not work on older VSCode)
> > * Twinny 3.4.0 with OOB settings + Disable Server Checks
> > 
> > Tested with both Windows workspace and WSL2 workspace (Ubuntu 22.04 LTS).
> > Many thanks @rjmacarthy, it's really snappy and responsive.
> 
> I am attempting this, but I just get a 404 error when trying to ask chat a question. currently it is using bridge networking but like you mentioned the only thing i changed is the server checks. i have also tried using the token it shows in the logs for the api calls. but neither method works.

I'm also getting a 404 using WSL, both in chat and code completions.  When I type in the editor, I see this on the command line indicating it's being hit:

[GIN] 2024/02/08 - 17:55:08 | 404 |     339.506µs |       127.0.0.1 | POST     "/api/generate"

Typing in the chat it responds with

🤖 twinny
Server responded with status code: 404

If I visit http://127.0.0.1:11435/ in a browser (I ran with OLLAMA_HOST port set to 11435 because the default port was already in use), then I see this in the browser:

Ollama is running

So I'm pretty sure the host and path are correct.  Not sure what to do from here.

**Comment by autoferrit** [comment]
> @sonicviz workspace as in WS workspace. And yes, Nvidia container toolkit I installed in WSL2 and issued the docker command from WSL2. Sorry, forgot to mention that in the original post. @ChainsawGarden In Twinny extension settings: ![image](https://private-user-images.githubusercontent.com/108837832/303362002-d46f796d-8ee0-4802-b693-350c2538919f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MzcxMjYsIm5iZiI6MTcwNzQzNjgyNiwicGF0aCI6Ii8xMDg4Mzc4MzIvMzAzMzYyMDAyLWQ0NmY3OTZkLThlZTAtNDgwMi1iNjkzLTM1MGMyNTM4OTE5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQwMDAwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjRhOTZkMGM0MDA1ZmMxMjVlZjQ5NjI3NTYwOWI3MjJlNGU1MjFjYTllYTI3NjI4MmQzOGM4OWRkODQ3ODU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tOcTJKg2EV7rLWn8YxzuwKMo-F86N3WbMc8f6W0VDjQ) @autoferrit try to start the docker from WSL2, this is what I did to be more exact. In docker desktop it shows like this: ![image](https://private-user-images.githubusercontent.com/108837832/303362409-8e022995-919e-4f4b-b504-085c13c4938b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MzcxMjYsIm5iZiI6MTcwNzQzNjgyNiwicGF0aCI6Ii8xMDg4Mzc4MzIvMzAzMzYyNDA5LThlMDIyOTk1LTkxOWUtNGY0Yi1iNTA0LTA4NWMxM2M0OTM4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQwMDAwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzVmNjMzNWY2YWZmNjc0MzhkYmUxNzg1NDc1NjkxYWQ3MzU2MzQzOWNmNTBmZDEzYmQ5NDc3NWQ0ZjU1ZmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EdshtsmJ9X5BZaZXHufkz91PQMmJv0rJ5_PQTNiSbAo) Also if I click the small icon next to the port, it opens in chrome fine: ![image](https://private-user-images.githubusercontent.com/108837832/303362548-c6a5c8cd-a0d7-45da-aea9-8e531a827426.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MzcxMjYsIm5iZiI6MTcwNzQzNjgyNiwicGF0aCI6Ii8xMDg4Mzc4MzIvMzAzMzYyNTQ4LWM2YTVjOGNkLWEwZDctNDVkYS1hZWE5LThlNTMxYTgyNzQyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQwMDAwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDYwMjU2ZThjM2QwYzI0M2M5MTAzZjZiY2M0MjBiMTFkMDYzMWJkOGQyMjcwMGU0OTE1OWZlMzg4ODYzNmQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7YpjQ1wpWx8mON7GbsIE0RjD39VNZgaz6cyf2Up2BRc)
> 
> Also, in docker I enabled WSL integration before doing anything (and restarted docker): ![image](https://private-user-images.githubusercontent.com/108837832/303363616-0b5b1d33-ab03-4490-93d9-4c7bbd936230.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MzcxMjYsIm5iZiI6MTcwNzQzNjgyNiwicGF0aCI6Ii8xMDg4Mzc4MzIvMzAzMzYzNjE2LTBiNWIxZDMzLWFiMDMtNDQ5MC05M2Q5LTRjN2JiZDkzNjIzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQwMDAwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzU4Yjc5Y2U3NWQ0MWNkZWJlNWIyNzU3OTA5N2ZlNDI0ZDc1ZTA5YTUzYTA3MjdjNmNmNzhlMDMxOTg5NDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-BljPbYT5bTQ2lmElA11mYBqUCf4gnDhl96CVr8YNKE)

similar to @jinglesthula i get lines in the log showing it gets to the generate endpoint and in the browser it shows working, but vscode gives me a 404

**Comment by rjmacarthy** [comment]
Just to add here, I added logging to twinny in the new version it's an option in the settings menu.  A 404 can be caused by the wrong model name, for example a space after the name can cause 404 on ollama server.

`"model": "deepseek-coder:6.7b-base-q5_K_M "` << 404 with extra space by accident
`"model": "deepseek-coder:6.7b-base-q5_K_M"` << without space is fine.

Maybe it helps?

**Comment by jinglesthula** [comment]
> Just to add here, I added logging to twinny in the new version it's an option in the settings menu. A 404 can be caused by the wrong model name, for example a space after the name can cause 404 on ollama server.
> 
> `"model": "deepseek-coder:6.7b-base-q5_K_M "` << 404 with extra space by accident `"model": "deepseek-coder:6.7b-base-q5_K_M"` << without space is fine.
> 
> Maybe it helps?

Oooh - nice! Thank you.  I will try that and see what it logs.

**Comment by jinglesthula** [comment]
Ok - so I didn't get around to trying the logging, but I did try something else that seemed to work better.

In my case, I'd installed ollama via the ollama-webui docker image.  What I didn't realize was that while the actual UI for it worked fine in the browser, the docker-compose.yaml file actually had separate containers running, one for ollama itself and another for ollama-webui.  

To get it to work, I had to add a port mapping to the ollama container.  Where I had

```
services:
  ollama:
    ...
    image: ollama/ollama:latest
```

I added this:

```
services:
  ollama:
    ...
    image: ollama/ollama:latest
    ports:
      - 11434:11434
```

After doing `docker-compose down`, then `docker-compose up` (rebuild the container), the VS Code twinny extension could then see it and I'm getting replies back in the chat.  🎉

**Comment by fsiler** [comment]
I am running `ollama.exe` as installed.  I've done `ollama pull codellama:7b-code` and `ollama pull codellama:7b-instruct`, and I've verified that I can poll HTTP on port 11434.  I left twinny in its default config.

I got one half-useful response when trying to get the model to explain, but all the other times it says it doesn't understand.  Any thoughts?  Ollama is using all the CPU, so it seems to be trying to do something, but Twinny isn't giving any useful results.

Output from `http://localhost:11434/api/tags`:

```json
{
  "models": [
    {
      "name": "codellama:7b-code",
      "model": "codellama:7b-code",
      "modified_at": "2024-02-25T18:04:20.8783953-06:00",
      "size": 3825910440,
      "digest": "fc84f39375bcfe7612f7636a681ebb13d54eb4466e6ea6da07b5d1c37b49994d",
      "details": {
        "parent_model": "",
        "format": "gguf",
        "family": "llama",
        "families": null,
        "parameter_size": "7B",
        "quantization_level": "Q4_0"
      }
    },
    {
      "name": "codellama:7b-instruct",
      "model": "codellama:7b-instruct",
      "modified_at": "2024-02-25T18:00:52.0941912-06:00",
      "size": 3825910662,
      "digest": "8fdf8f752f6e80de33e82f381aba784c025982752cd1ae9377add66449d2225f",
      "details": {
        "parent_model": "",
        "format": "gguf",
        "family": "llama",
        "families": null,
        "parameter_size": "7B",
        "quantization_level": "Q4_0"
      }
    },
    {
      "name": "codellama:latest",
      "model": "codellama:latest",
      "modified_at": "2024-02-25T17:52:14.9795548-06:00",
      "size": 3825910662,
      "digest": "8fdf8f752f6e80de33e82f381aba784c025982752cd1ae9377add66449d2225f",
      "details": {
        "parent_model": "",
        "format": "gguf",
        "family": "llama",
        "families": null,
        "parameter_size": "7B",
        "quantization_level": "Q4_0"
      }
    },
    {
      "name": "gemma:7b",
      "model": "gemma:7b",
      "modified_at": "2024-02-25T17:37:29.5748369-06:00",
      "size": 5202317200,
      "digest": "430ed3535049f562814f612a653457ba9fd390cccc77a94ab88964b8d8fd18a8",
      "details": {
        "parent_model": "",
        "format": "gguf",
        "family": "gemma",
        "families": [
          "gemma"
        ],
        "parameter_size": "9B",
        "quantization_level": "Q4_0"
      }
    }
  ]
}
```

**Comment by fsiler** [comment]
> I am running `ollama.exe` as installed. I've done `ollama pull codellama:7b-code` and `ollama pull codellama:7b-instruct`, and I've verified that I can poll HTTP on port 11434. I left twinny in its default config.
> 
> I got one half-useful response when trying to get the model to explain, but all the other times it says it doesn't understand. Any thoughts? Ollama is using all the CPU, so it seems to be trying to do something, but Twinny isn't giving any useful results.
> 
> Output from `http://localhost:11434/api/tags`:
> 
> ```json
> {
>   "models": [
>     {
>       "name": "codellama:7b-code",
>       "model": "codellama:7b-code",
>       "modified_at": "2024-02-25T18:04:20.8783953-06:00",
>       "size": 3825910440,
>       "digest": "fc84f39375bcfe7612f7636a681ebb13d54eb4466e6ea6da07b5d1c37b49994d",
>       "details": {
>         "parent_model": "",
>         "format": "gguf",
>         "family": "llama",
>         "families": null,
>         "parameter_size": "7B",
>         "quantization_level": "Q4_0"
>       }
>     },
>     {
>       "name": "codellama:7b-instruct",
>       "model": "codellama:7b-instruct",
>       "modified_at": "2024-02-25T18:00:52.0941912-06:00",
>       "size": 3825910662,
>       "digest": "8fdf8f752f6e80de33e82f381aba784c025982752cd1ae9377add66449d2225f",
>       "details": {
>         "parent_model": "",
>         "format": "gguf",
>         "family": "llama",
>         "families": null,
>         "parameter_size": "7B",
>         "quantization_level": "Q4_0"
>       }
>     },
>     {
>       "name": "codellama:latest",
>       "model": "codellama:latest",
>       "modified_at": "2024-02-25T17:52:14.9795548-06:00",
>       "size": 3825910662,
>       "digest": "8fdf8f752f6e80de33e82f381aba784c025982752cd1ae9377add66449d2225f",
>       "details": {
>         "parent_model": "",
>         "format": "gguf",
>         "family": "llama",
>         "families": null,
>         "parameter_size": "7B",
>         "quantization_level": "Q4_0"
>       }
>     },
>     {
>       "name": "gemma:7b",
>       "model": "gemma:7b",
>       "modified_at": "2024-02-25T17:37:29.5748369-06:00",
>       "size": 5202317200,
>       "digest": "430ed3535049f562814f612a653457ba9fd390cccc77a94ab88964b8d8fd18a8",
>       "details": {
>         "parent_model": "",
>         "format": "gguf",
>         "family": "gemma",
>         "families": [
>           "gemma"
>         ],
>         "parameter_size": "9B",
>         "quantization_level": "Q4_0"
>       }
>     }
>   ]
> }
> ```

update- now completing some stuff but stopping short, eg,

```
what is a python dataclass used for?

🤖 twinny
A Python data class is a class that contains only instance variables and no methods. It is used to define a structure of data that can be serialized and deserialized using the built-in json module in Python. Data classes are similar to regular classes, but they have some additional features that make them useful for working with JSON data.

Here are some of the key benefits of using a data class:

Easy to use: Data classes are designed to be easy to use and require minimal boilerplate code. You```

**Comment by rjmacarthy** [comment]
Please try to update to the latest Ollama and Twinny and test again, it has been migrated to the Ollama OpenAI api and might be better.  Many thanks.

**Comment by rjmacarthy** [comment]
Stale
