### ISSUE TITLE
Open VSX Support

### ISSUE THREAD

**Issue by orkutmuratyilmaz** [rjmacarthy/twinny#71]
Hello and thanks for this beautiful repo.

Can you publish the extension on [Open VSX](https://open-vsx.org/) too? I'm using [VSCodium](https://vscodium.com/) and it would be nice to get updates automatically.

Best,
Orkut

**Comment by rjmacarthy** [comment]
Hey thanks.

Yes I will make sure to to this too.

Many thanks

**Comment by badetitou** [comment]
I agree, that would be super great

**Comment by rjmacarthy** [comment]
Done, thanks!

https://open-vsx.org/extension/rjmacarthy/twinny

**Comment by badetitou** [comment]
@rjmacarthy you can setup a GitHub action if you want to automate the publish on open-vsx and the marketplace of vscode like this if you want

https://github.com/badetitou/vscode-pharo/blob/main/.github/workflows/publish.yml

It updates the build for each new tag (so every release of the code)

**Comment by rjmacarthy** [comment]
Hey @badetitou thanks, I currently have no free Github action credits left for this month, I used them all on something else already >.<. When they roll over I will try to implement it.

**Comment by orkutmuratyilmaz** [comment]
thank you @rjmacarthy for adding:)
