### ISSUE TITLE
add gpt-4-turbo-preview

### ISSUE THREAD

**Issue by bjornjorgensen** [rjmacarthy/twinny#73]
Hi, I will like to have support for models like gpt-4-turbo-preview

**Comment by rjmacarthy** [comment]
Hey, thanks for the support and interest.

Unfortunately, this is a difficult one for me as I wanted this extension to be working of local models only i.e not share information with third party providers like OpenAI.  I guess that it could be implemented however it's not a priority for me right now.  Feel free to make a PR if you are willing to implement it.

Many thanks,

**Comment by rjmacarthy** [comment]
Adding support for GPT is not a priority for now.
