### ISSUE TITLE
If the ollama server responds with status code 404 response sounds like AI responding when AI wasn't the writer

### ISSUE THREAD

**Issue by brunoais** [rjmacarthy/twinny#76]
**Describe the bug**

I opened the chat window and I sent a message. As expected (because I didn't install the model yet), the request doesn't lead to any useful result.
However, twinny displays in the UI text which can be plausible as the AI response:

> Sorry, I don’t understand. Please try again.

**To Reproduce**

1. Install ollama anew and start serving.
2. Install twinny in the editor.
3. Open the sidebar
4. Type something to the bot.
5. Twinny answers `Sorry, I don’t understand. Please try again.`

**Expected behavior**
I'd expect some different icon that resembles a server and the name `system` or similar mentioning, for example:

> 🖥️ ollama
> Server returned error: "model 'codellama:A7b-instruct' not found, try pulling it first"

**Screenshots**
![image](https://github.com/rjmacarthy/twinny/assets/639467/0269c00d-e025-4909-9b2b-0c57a956aa62)
![image](https://github.com/rjmacarthy/twinny/assets/639467/fa5b66f6-d59b-4a5d-be8c-0d62eb1b3b2e)

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

**Comment by rjmacarthy** [comment]
Hey thanks for the interest and support.

This is a great suggestion, do you think it would be best to show the error instead?

**Comment by brunoais** [comment]
But showing the error is what I suggested, I believe 
![image](https://github.com/rjmacarthy/twinny/assets/639467/78c2742b-b56c-4e32-960d-b90b70aa588a)
