### ISSUE TITLE
Add contextual `when` to keyboard shortcuts

### ISSUE THREAD

**Issue by brunoais** [rjmacarthy/twinny#77]
**Is your feature request related to a problem? Please describe.**
I'd like to reuse keyboard shortcuts that are already used for something else for twinny.
In my case,
1. `CTRL+SHIFT+Enter` to cancel bot generating text.
2. `CTRL+SHIFT+Space` to prompt the bot to try to guess what code comes next.

However, those keys are already assigned to other shortcuts which I also would like having for those shortcuts.
However, they don't apply to the same contexts.

**Describe the solution you'd like**
I'd like the provided shortcuts to already contain context evaluation from the get-go so the shortcuts only apply when the context makes sense.
For example, the key so the bot stops, can be limited only to the context of the bot generating a message (and 0.5-1s grace period). See:
https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context

The key to prompt the bot to trigger an inline suggestion can be only active when the user is focusing on the editor (or other similar contexts).

**Describe alternatives you've considered**
Make the shortcuts more complex, such as 2 stage shortcut to try to avoid the clash. Takes a long time if I keep wanting suggestions but not suggestions on each key press.

**Additional context**
(Kept the original shortcuts in this shot so you can identify them more easily)
![image](https://github.com/rjmacarthy/twinny/assets/639467/f52e9505-5f76-4e91-b358-d9ef131f623a)

Thank you for this tool!

**Comment by rjmacarthy** [comment]
Thanks for the support, I have just added contextual `when` clauses to the keybindings.

**Comment by brunoais** [comment]
Thank you very much!
