### ISSUE TITLE
Add support for multi-language files

### ISSUE THREAD

**Issue by brunoais** [rjmacarthy/twinny#78]
**Is your feature request related to a problem? Please describe.**
Yes.

I'm trying to edit a PHP file which contains HTML embedded which contains some javascript embedded. Twinny's recommendations appear to assume I want PHP and even that the code is PHP when I'm editing the javascript portion.

**Describe the solution you'd like**
There are 2 separate and different difficulty level possibilities for this.

1. Identify that it's a multi-language file type and allow the user to clarify (in the chat box, could be the first word, for example) But it can also be a dropbox that is easily accessible.
2. Identify the language where the cursor is at which is used when prompting the bot
2.1. Doing this half arsed might do so-so reasonable results.... Maybe
2.2. Doing this for real (but doing that well is a PITA and I don't recommend)

**Describe alternatives you've considered**
I'm unable to find viable alternatives.

**Comment by rjmacarthy** [comment]
Hey thanks for the suggestion this is a good idea.

To be honest I am not sure how these small models handle FIM for multiple languages in the same prompt, probably not well is my assumption.  

It might be easier in the chat as we can have a drop down as you mention.  In terms of detecting the current language from the editor, I am not sure what the best approach would be currently it might require more advanced techniques to establish it.

**Comment by brunoais** [comment]
> To be honest I am not sure how these small models handle FIM for multiple languages in the same prompt, probably not well is my assumption.

They aren't good with multiple languages in the same place but usually it's not required to have a lot of content outside the small area to get suggestions so usually it can adapt to the situation because (mostly) all it will see is that singular embedded language's code (E.g. javascript in an HTML document) or it's so small the help isn't useful.

> It might be easier in the chat as we can have a drop down as you mention.

Yep. That's what I recommend too. Maybe with some kinks to make it fast to swap out, for example, fast tabbing or a shortcut only available in that window to open the dropdown.
For now, I'd just have a hardcoded list of languages for each defined language and accept PRs to make them more complete. For example, for PHP:

1. PHP
2. HTML
3. Javascript
4. CSS

The order is designed to make the most likely language to encounter in each language mode. In PHP, PHP should be the most common. Followed by HTML (because JS and CSS, most likely will be in external files). Then I went with js just because non-AI has gotten really good with CSS, so js is most likely to be asked about.

For other file types, for example, HTML, would be the 2,3,4 of the previous list.

A very different example: jinja2. Would probably get the same set as PHP except the 1st one is jinja2 or just straight up move the jinja2 to 2nd and select HTML 1st instead (Maybe leave the jinja2 help to the non-AI... Not sure. Dunno how good the AI is with jinja2).

There's a lot that would be correct so I'd start with some languages that are "multi-language" and hardcode possibilities for the drop down. After ppl start using this more, maybe someone will have good ideas how to proceed to viably please people.

For automatic detection... I'd probably start with half-arsed regex or similar to figure out some identifiers but I wouldn't try yet. It's full of issues and annoying (to the user) edge-cases that are not worthwhile yet.

------

For implementation, I'd just have a very simple translation table (can be a js object) from a name and an array of options for the drop box. If not defined in the translation table, just use the language provided.

For now, I'd be happy with:

1. PHP
2. HTML
3. jinja-py

There might be more and ppl with other embeds but this should work fine for now.
What do you think?

**Comment by AntonKrug** [comment]
`I'm unable to find viable alternatives.`

You could make your own buttons for each language being hardcoded. `Explain JS`, `Explain HTML` and enable/disable the ones you do not want at that specific moment so it's not clutering the buttons too much. And you use these dedicated buttons to request explanation from whitin that given language instead of having one generic button like now:

```
{{{systemMessage}}}
Explain the following code;
{{{code}}}
Do not waffle on. The language is:
{{language}}
 ```

**Comment by rjmacarthy** [comment]
stale
