### ISSUE TITLE
Stop automatic scrolling of chat content

### ISSUE THREAD

**Issue by ericvrp** [rjmacarthy/twinny#79]
When interacting in the chat window the content area always scrolls whatever I am reading out of view at the top.

Can we prefend this?

**Comment by rjmacarthy** [comment]
Hey, thanks for the interest and support.

This is a great suggestion I will implement it soon, unless a PR comes my way first.

- Add a button when generating to skip the the bottom, by default it's enabled but if scrolled it's disabled.

**Comment by rjmacarthy** [comment]
Hey, I just added a new button to the chat interface in version `3.3.8` which allows the user to enable/disable the auto-scroll.

https://github.com/rjmacarthy/twinny/pull/89
