### ISSUE TITLE
Location of accept/copy buttons

### ISSUE THREAD

**Issue by ericvrp** [rjmacarthy/twinny#80]
I like to read the suggested code and then accept/copy so I find myself constantly scrolling back to find those buttons.

Can we move those to below the suggested code? Or alternatively have them in both locations? Have a feature flag in settings for the location(s) is also an option. But in that case an advanced settings area might start making sense.

**Comment by rjmacarthy** [comment]
This is a great suggestion, moving the buttons to the bottom makes a lot of sense.  This was a quick and dirty solution when I first implemented it. 

Many thanks,

**Comment by rjmacarthy** [comment]
Hey @ericvrp in version 3.3.4 the buttons are at the bottom of the code blocks.

Many thanks,
