### ISSUE TITLE
<newbie-disclosure> I've installed twinny with VS code and have the chat interface working; however, the code autosuggest (fill in the middle) is not activating.

### ISSUE THREAD

**Issue by calirails** [rjmacarthy/twinny#81]
**Describe the bug**
**Reiterating: This may be my misunderstanding rather than a bug.**

I can get twinny to respond to my questions in the chat interface within VSCode; however, nothing triggers via autosuggest as I write code. I verified that I have the two prerequisite models that are supported (screenshot below) but don't know how to ensure both are running -- without collision -- and respond to Twinny at its preconfigured URLs.
<img width="486" alt="image" src="https://github.com/rjmacarthy/twinny/assets/942698/fafd2471-0684-4703-a68e-a777ea6a158a">

Questions: 
a) Is it expected for me to have to explicitly run the ollama model(s) before Twinny initializes? 

b) How do I spawn Ollama to serve both models at URLs without colliding so that Twinny can reach them both? I've checked the configuration and it appears there is a root url (http://localhost), path (/api/generate) and port (11434) as seen here. 
<img width="718" alt="image" src="https://github.com/rjmacarthy/twinny/assets/942698/5a8f9542-f358-4f43-9f0b-0012c101ae75">

Perhaps expected: after terminating the terminal session that was running `$ollama run codellama` the Twinny chat stopped responding. I then executed both `ollama $run codellama:7b-code` as well as `$run codellama:7b-instruct` concurrently but that did not activate the chat or autosuggest within VS Code. Shutting down VSCode didn't help either.

It appears the only feature I have is chat and will only work if (pre) spawn $ollama run codellama. Do I have it corect that doing so spawns the default codellama (latest) model rather than the fine tuned models for chat and autosuggest. Is this correct?

**To Reproduce**
1. Spawn VS Code with my sample project; or any for that matter.
2. Spawn ollama model(s); e.g. 'ollama run codellama'
3. Click on the Twinny Extension
4. Type in a question: 'write an email regex matcher function for validation`
5. Open a typescript file and type in the following `const adder = (op1: number, op2: number): number => op1 + op2;

**Expected behavior**
Along with the Twinny chat interface, I also expect autosuggest to activate and display code suggestions as I type in code.

**Desktop (please complete the following information):**
 - OS: OSX Sonoma 14.2.1 (23C71)
 - Browser [e.g. chrome, safari]: chrome but not relevant for this filing.
 - Version: Twinny version: **v3.3.0**
 - VSCode: **version 1.85.2**

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: [N/A
 - Browser N/A
 - Version N/A

**Additional context**

**Comment by calirails** [comment]
Resolving: My mistake.

The TLDR;
My ollama server must have crashed hard and caused the side effects. I rebooted and was able to run ollama $run codellama:7b-code as well as $run codellama:7b-instruct concurrently and saw that Twinny is working great.

**Comment by calirails** [comment]
Without updating Twinny or its settings, Ollama, or VS Code, my integration for chat and code completion has suddently stoppped working. 

I have verified that the robot head icon is visible in the bottom right of the VS Code tray that indicates Twinny is activated. Despite this, Twinny is not responding with any answers in the chat and just animates a spinning cursor. The code completion has stopped suggesting as well. 

At one point the Twinny extension seeemed to auto spawn something or to load the models but it doesn't seem to do that anymore.

What are the commands I must run manually in the shell to help Twinny along?

**Comment by rjmacarthy** [comment]
The endpoint is wrong. Please use Ollama OpenAI chat endpoint. /v1/chat/completions

**Comment by calirails** [comment]
@rjmacarthy: I appreciate the response. Reinstalling and restarting ollama fixed my problems. Thank you & closing issue.
