### ISSUE TITLE
Should FIM Model Name deepseek-coder:6.7b-instruct-q4_K_S work?

### ISSUE THREAD

**Issue by ericvrp** [rjmacarthy/twinny#84]
I get no FIM using deepseek-coder:6.7b-instruct-q4_K_S , also not when selecting the deepseek Fim template format.
Do I use the correct model?

**Comment by ericvrp** [comment]
Hmm - referting back to codellama:7b-code also doesn't FIM anymore.

**Comment by rjmacarthy** [comment]
Hey, please try a deepseek base model I have been using `deepseek-coder:6.7b-base-q5_K_M` successfully for FIM.

**Comment by ericvrp** [comment]
that base model did work . thanks
