### ISSUE TITLE
Suggestion: Automatically publish new versions (tagged commits)

### ISSUE THREAD

**Issue by brunoais** [rjmacarthy/twinny#90]
FYI: If you are OK with automation, you can setup a GitHub action to publish on both open-vsx and vscode marketplace.

**Example to publish on each new tag:**
https://github.com/badetitou/vscode-pharo/blob/main/.github/workflows/publish.yml
**A more detailed example:**
https://github.com/HaaLeo/vscode-timing/blob/master/.github/workflows/cicd.yml#L1
**The instructions of the action are here:**
https://github.com/HaaLeo/publish-vscode-extension

**How to make a secret:**
https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository

(credit to @badetitou for the idea https://github.com/rjmacarthy/twinny/issues/71#issuecomment-1927084174)

**Comment by AntonKrug** [comment]
@rjmacarthy would you like to me look into it and help? Maybe having a external self-hosted runners so it wouldn't take your credit and building it a container image so swapping between self-hosted runners or GH-hoseted runners would be easier?

**Comment by rjmacarthy** [comment]
Hey @AntonKrug sure if you are able to help that would be great.  I was going to tackle this when the monthly credits roll over. I think we can stick with github actions for now, perhaps with push to `main` / `master` branch and will develop against `dev` branch in the future and merge for releases.

Many thanks,

**Comment by rjmacarthy** [comment]
I updated this now so that commits to `main` branch will trigger deployments.  The `development` branch will be used for tracking pre-release status.  I am having issues generating a token on OpenVSX right now but I opened an issue for it.

https://github.com/eclipse/openvsx/issues/866

**Comment by rjmacarthy** [comment]
This is now completed and working on pushes to `main`.  Thank you for the suggestion and help.
